longhorn/longhorn

README.md, deploy/example-backupstore.yaml, deploy/example.yaml
Major updates:
1. Longhorn will now run in the `longhorn-system` namespace by default.
2. Improvement on Longhorn Driver includes dependency check when started and
automatic static-linked jq installation
3. Use ganesha as the NFS server for testing to remove the dependency of
`nfs-kernel-server` on the host.
=> Update deploy example.yaml

README.md, docs/restore_statefulset.md
This PR adds documentation for restoring volumes from the `Longhorn UI` in order to use them in Kubernetes `Stateful Sets`. The instructions have been split into two sections for `csi` and `flexvolume` drivers, and both at the end lead back to the same common instructions used to deploy the `Persistent Volume Claims` and the actual `Stateful Set`.
This PR resolves #166.
=> Add documentation for restoring to Stateful Set

README.md
Based on the issue #279, new documentation added with the examples of AWS S3 backup store configuration.
=> AWS S3 backup store settings added to READ.md

deploy/longhorn.yaml
There is no function change from v0.3.0 to v0.3.1-rc1. Don't want to trigger
unnecessary upgrade process for the engine.
=> deploy: Keep the engine at v0.3.0

README.md, deploy/longhorn.yaml, docs/chart.md, docs/gke.md, docs/troubleshooting.md, scripts/environment_check.sh
https://github.com/rancher/longhorn/issues/266
@yasker I feel as though we may want to put this in a `v0.3` branch. Updating the master branch docs before releasing `0.3.1` is going to cause confusion for existing `0.3.0` users. Worse, it causes problems if user tries to deploy `longhorn.yaml` in master branch before we update the images.
Our docs all point to resources in the master branch as opposed to a specific release, so we have to be careful...
=> Update docs relevant to FlexVolume dirpath setting

README.md
Engine image: rancher/longhorn-engine:v0.3.3
Manager image: rancher/longhorn-manager:v0.3.3
UI Image: rancher/longhorn-ui:v0.3.3
New features:
1. #299 Support set the default number of replicas (replica count) and dynamic adjust replica count of an attached volume.
2. Live upgrade for Engine image became beta. Upgrade from Engine v0.3.0 to v0.3.3 can be done without volume downtime (except if you need the fix for #324 2TB volume size limitation)
Notice Longhorn Engine has been updated to v0.3.3. Please follow the steps [here](https://github.com/rancher/longhorn/blob/master/docs/upgrade.md#upgrade-engine-images) to upgrade engines.
See [here](https://github.com/rancher/longhorn/milestone/6?closed=1) for the list of bugs fixed.
=> Longhorn v0.3.3 release

README.md, chart/.helmignore, chart/Chart.yaml, chart/README.md, chart/app-readme.md, chart/questions.yml, chart/templates/NOTES.txt, chart/templates/_helpers.tpl, chart/templates/clusterrole.yaml, chart/templates/clusterrolebinding.yaml, chart/templates/crds.yaml, chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/ingress.yaml, chart/templates/postupgrade-job.yaml, chart/templates/serviceaccount.yaml, chart/templates/storageclass.yaml, chart/templates/tls-secrets.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml, deploy/longhorn.yaml, docs/dr-volume.md, docs/k8s-workload.md, docs/snapshot-backup.md, examples/storageclass.yaml, uninstall/uninstall.yaml
Highlights:
1. Users now can use Disaster Recovery Volume support (#495 ) to recover
the volume in another Kubernetes cluster with defined RTO and RPO. See
[here](https://github.com/rancher/longhorn/blob/v0.5.0/docs/dr-volume.md)
for details
2. Users now can see Kubernetes workload information and create PV/PVC in
Longhorn UI (#461 ) .See
[here](https://github.com/rancher/longhorn/blob/v0.5.0/docs/k8s-workload.md)
for details
3. Users now can set backup scheduling in the storage class (#362)
4. We now add the Helm chart in the Longhorn repo, in addition to Rancher
Apps. (#445 )
See all the issues resolved in v0.5.0 at:
https://github.com/rancher/longhorn/milestone/3?closed=1
The volume engines would need to upgrade to v0.5.0 as well.
Please follow the instruction to upgrade engines.
=> Longhorn v0.5.0 release

docs/snapshot-backup.md
The docs say to use `s3://backupbucket@us-east-1/backupstore` but the app already appears to create `backupstore` in the bucket. This means we end up with `backupbucket/backupstore/backupstore/volumes/...`
This edit removes `backupstore` from the S3 path.
=> remove backupstore from S3 path

docs/csi-config.md
Making the language a bit clearer rather than using vX.Y.Z- (including/not including) and vX.Y.Z+ everywhere.
https://github.com/longhorn/longhorn/commit/1f197678e13dcf65bce233b9d13628a3c1d06b5c#commitcomment-36092133
=> Use more verbose language for clarity

deploy/longhorn.yaml, docs/restore_statefulset.md, docs/storage-tags.md, examples/storageclass.yaml
I can't find a single "spec" for the parameters, so I figure it's best to explain it in the examples and documentation. It took me a while to find the units in the code.
I'm still curious the mechanism of it- is this for a single replica before it gets replaced? What are the hazards of setting it too low or high?
=> add units for the staleReplicaTimeout

chart/questions.yml
https://github.com/longhorn/longhorn/issues/1068
Overprovision factor to 200%.
Minimal available disk to 25%.
=> chart: Change default setting for storage related options

chart/templates/deployment-driver.yaml, chart/values.yaml
I was deploying longhorn on a local single-node cluster for local development and I didn't want many replicas. Let me know if this is something not desirable.
=> feat: add csi.resizerReplicaCount to chart values

chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, deploy/longhorn.yaml
When pod security policies are used, the typical default of a very restricted policy does not allow root permissions. Even when a more permissive policy is assigned to the service account, we need to inform k8s that we need root permissions so that the correct policy can be selected. This PR does that.
Note: when PSPs are enforced, one still needs to explicitly set the correct PSP for both the default account in the longhorn-system namespace (allow root user) and the "longhorn-service-account" (allow everything).
=> Set securityContext for deployer and ui (for use with PSP)

README.md
Attempting to use longhorn with NFSv3 for backuip causes errors related to rpc.statd, which is not managed by longhorn processes.  Longhorn works properly with NFSv4 servers only.
=> Update README.md to specify NFS version is v4

examples/rwx/01-security.yaml, examples/rwx/02-longhorn-nfs-provisioner.yaml, examples/rwx/03-rwx-test.yaml
Below are the example deployment for nfs on top of a longhorn volume.
The nfs volume can then be used in RWX mode.
**For quicker pod eviction:**
We add tolerations so that nfs provisioner pod gets evicted from a failing
node after 60 second + 30 grace period (relevant for va recovery policy).
Add liveness + readyness probe, so that no traffic gets routed to a failed
nfs server. Disable device based fsids (major:minor) since our block device
mapping can change from node to node, which makes the id's unstable.
**To enable nfs reconnection to the new pod ip via the service:**
We add noresvport to the nfs mount options
This makes the nfs client use a new src port for each tcp reconnect.
This way after a crash the faulty connection isn't kept alive in the
connection cache (nat). This should …
=> Add example deployment of nfs on top of a longhorn for RWX volumes

enhancements/20200625-volume-deletion-flows.md
This PR adds a Longhorn Enhancement Proposal for how to handle `Volume` deletion in the cases that a `Volume` has associated resources in `Kubernetes` or is `Attached`. The changes outlined in this proposal will make deletion of `Volumes` in these situations safer by avoiding leaving leftover `Persistent Volumes` or `Persistent Volume Claims` that would be unusable and warning users about possible repercussions as a result of deleting an attached `Volume`.
This proposal provides a solution for the cases described in #520.
=> Add Longhorn Enhancement Proposal for handling Volume deletion

chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, dev/scripts/update-image-pull-policy.sh
We changed the imagePullPolicy to IfNotPresent so that user can easily install Longhorn in air-gap installation.
Also added a bash script for the developer to quickly change all the magePullPolicies back to Always.
longhorn/longhorn#1491
=> dev, deploy, chart: change imagePullPolicy to IfNotPresent for manager, ui, driver deployer.

enhancements/20200701-backupstore-file-locks.md
The idea is to implement a locking mechanism that utilizes the backupstore,
to prevent the following dangerous cases of concurrent operations.
1. prevent backup deletion during backup restoration
2. prevent backup deletion while a backup is in progress
3. prevent backup creation during backup deletion
4. prevent backup restoration during backup deletion
The locking solution shouldn't unnecessary block operations, so the
following cases should be allowed.
1. allow backup creation during restoration
2. allow backup restoration during creation
The locking solution should have a maximum wait time for lock acquisition,
which will fail the backup operation so that the user does not have to wait
forever.
The locking solution should be self expiring, so that when a process dies
unexpectedly, …
=> enhancements: Add LEP for backupstore file locks

examples/rwx/01-security.yaml, examples/rwx/02-longhorn-nfs-provisioner.yaml
1. Use different names for the 2 roles
(and the related role bindings)
2. Make sure the role binding namespace is the same as the
namespace where nfs provisioner is deployed
=> example: Fix example rwx

chart/Chart.yaml
This PR updates the list of maintainers in the Longhorn chart such that it now refers to the Longhorn maintainers and @yasker  instead of referring to Rancher.
=> Update chart maintainers

scripts/load-images.sh, scripts/save-images.sh
When user provides an invalid flag, print out error message and help menu instead of looping forever
longhorn/longhorn#1419
=> scripts: fix the scripts load-images.sh and save-images.sh in the case user provides invalid flags

chart/questions.yml
This makes sure that the Rancher chart correctly passes the user-provided CSI Driver Registrar image registry value to `values.yaml` and therefore to the yaml template `deployment-driver.yaml`
longhorn/longhorn#1590
=> chart: change the CSI Driver Registrar image variable in question.yaml to have the same name as in values.yaml

chart/Chart.yaml
This PR updates a few attributes in `Chart.yaml` to improve the chart listing on Helm Hub and Artifact Hub. Specifically:
- The chart icon has been updated to use the version without text.
- The chart description no longer mentions Rancher since Longhorn is now a CNCF project.
=> Update chart icon and description

chart/templates/storageclass.yaml
Since the storage.k8s.io/v1 API, the annotation for is-default-class is no longer in beta and was deprecated.
https://github.com/kubernetes/kubernetes/pull/40088
=> fix: remove beta annotation from storage class

enhancements/20200819-keep-a-local-replica-to-engine.md
=> enhancement: Add LEP 'support Data Locality option to keep a replica local to the engine'

dev/scripts/lm-update.sh, dev/scripts/update-image-pull-policy.sh
To include a way to restart every Longhorn components automatically with
the latest image.
1. Now `lm-update.sh` will set `imagePullPolicy: Always` for the manager
and the driver.
2. Now update-image-pull-policy.sh will update the `imagePullPolicy` for
all the running deployments and daemonsets in the `longhorn-system`
namespace, including CSI components.
=> dev scripts: update lm-update.sh and update-image-pull-policy.sh

chart/questions.yml, chart/templates/storageclass.yaml, chart/values.yaml
StorageClass in chart lacks ability to define `retainPolicy` which is a pain in some sensible environments.
This PR solves it by adding a setting and maintaining the previous behavior as default (`Delete`)
=> StorageClass: add reclaimPolicy

chart/questions.yml, chart/templates/daemonset-sa.yaml, chart/templates/default-setting.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/registry-secret.yml, chart/templates/uninstall-job.yaml, chart/values.yaml
To avoid confusing user, we move the registry secret setting outside of default setting section. Now, user will set registry secret setting in `privateRegistry.registrySecret`
Also, we change `imagesPullPolicy` of `longhorn-post-upgrade` job and `longhorn-uninstall` job to `IfNotPresent` so that user can upgrade/uninstall Longhorn using Helm in airgap environment. 
longhorn/longhorn#1670
longhorn/longhorn#1986
=> change registry secret location

chart/templates/_helpers.tpl, chart/templates/clusterrolebinding.yaml, chart/templates/daemonset-sa.yaml, chart/templates/default-setting.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/ingress.yaml, chart/templates/postupgrade-job.yaml, chart/templates/psp.yaml, chart/templates/registry-secret.yml, chart/templates/serviceaccount.yaml, chart/templates/storageclass.yaml, chart/templates/tls-secrets.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
**Description:**
When using the longhorn as a sub-chart the release namespace is not always going to be the longhorn-system, we should allow the user to specify override namespace in this scenario.
**Solution:**
Add `namespaceOverride` value that allows the user to override the Release.Namespace when it is not using the `longhorn-system`
**related issue:**
https://github.com/longhorn/longhorn/issues/2031
=> Add override namespace value

chart/templates/crds.yaml
Will find another way to migrate the CRD file later.
Longhorn #2035
=> chart: Remove the annotation which causes CRDs not removed during uninstallation

chart/Chart.yaml, chart/README.md
Since we update the CRD apiVersion to apiextensions.k8s.io/v1, the
minimal Kubernetes version requirement is v1.16 now.
Longhorn #2061
=> chart: Update Kubernetes version requirement for chart

chart/questions.yml, chart/values.yaml
We switched from fedora to an ubuntu base image, to support the security
scanner.
longhorn/longhorn#2111
=> Update default share-manager image to v1_20210106

chart/templates/daemonset-sa.yaml
The host's `/var/run/nscd` leaking into the pod and it caused the DNS lookup failure.
https://github.com/longhorn/longhorn/issues/2200
=> Remove mount /var/run from host to avoid DNS lookup failure

chart/questions.yml, chart/values.yaml
Include
- Patched nfs-ganesha v3.3 to fallback to ipv4 when ipv6 is not available.
https://github.com/longhorn/longhorn/issues/2197
- Fix for pod hanging at ganasha server error due to missing /etc/mtab file in Ubuntu image.
https://github.com/longhorn/longhorn/issues/2111
Test: https://github.com/longhorn/longhorn/issues/2197#issuecomment-788595045
=> Update default share-manager image to v1_20210302

chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
Now that we only watch/update managed components, we should allow user to specify Helm values for user deployed components (manager, driver, UI).
longhorn/longhorn#2120
=> Allow user to specify priority class and tolerations for Longhorn UI, Driver, Manager

chart/templates/ingress.yaml, chart/values.yaml
This PR adds support for `ingressClassName` on `Ingress` object in the Helm Chart.
See related [blog post](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/)
Fixes #2257
=> Add support for ingressClassName in helm chart

chart/questions.yml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml, deploy/release-images.txt
Include:
* Fix rwx mount ownership reset to nobody (https://github.com/longhorn/longhorn/issues/2357)
=> Update default share-manager image to v1_20210406

chart/questions.yml, chart/templates/daemonset-sa.yaml, chart/templates/default-setting.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
This feature allow user to deploy Longhorn only on a specific
set of nodes
Modification:
1. Remove the `toleration` and `priority class` settings from `question.yaml`. 
User cannot set `toleration` for the user-deployed components  (manager, UI, Driver) from the `question.yaml` because Rancher chart [doesn't allow question of type `array`](https://github.com/rancher/rancher/issues/24918). Therefore, user must choose to `Edit as YAML` in Rancher Ui when install Longhorn . On the other hand, if user wants set `toleration` and `priority class` for Longhorn, they must set them for both system managed components and user-deployed components. Therefore, to avoid the mistakes, we remove everything from the `question.yaml` and user can edit the yaml to specify value for both system managed …
=> Allow user to set node selector for system managed components, manager, UI, driver deployer

chart/Chart.yaml
Use .png as a chart icon to make it visible on the rancher server.
My forked longhorn charts repo
Rancher server icon
https://github.com/rancher/charts/issues/1058
=> Update chart icon

chart/templates/tls-secrets.yaml
This fixes longhorn/longhorn#2615.
`$ cat values-fix.yaml`
```yaml
ingress:
enabled: true
ingressClassName: nginx
host: xip.io
tls: true
tlsSecret:
name: longhorn-tls
certificate: |
-----BEGIN CERTIFICATE-----
MIIGUzCCBDugAwIBAgICAMswDQYJKoZIhvcNAQELBQAwZDELMAkGA1UEBhMCQ1ox
GzAZBgNVBAoTEkNlc2tlIGRyYWh5LCBhLiBzLjEmMCQGA1UECxMdQ0QgLSBJbmZv
AXherC8keWXJ+9dmeG5PkU5gFHFKDc3gnTeYnD2PaagwaD/StqEk
-----END CERTIFICATE-----
key: |
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAp8uLTKyoizTbuj4axag7xGx6yxGCcAlQWt25SQFPfA1H/o2v
Vzz40D9RNjezIjDRw4BEarYmJ8qu3TkAdhIpRz0eLy4qC1CoyRUvyjwZglJt0MXK
+UZlBYbzNVp72UVrwkC1irCjGta9bkZuKZc6HaX+HiOxKpH3WZYO
-----END RSA PRIVATE KEY-----
```
```bash
$ helm install longhorn ../jC3rny/longhorn/chart/ --values values-fix.yaml --dry-run --debug
---
apiVersion: v1 …
```
=> Fix ability to provide own tls certificate for ingress.

chart/templates/tls-secrets.yaml
cherry-pick to v1.1.2 branch for https://github.com/longhorn/longhorn/pull/2616
Related to issue #2615.
Signed-off-by: Jan Černý <jC3rny89@Gmail.com>
=> [cherry-pick-v1.1.2] fix chart ingress tls secret

scripts/environment_check.sh
instead of just the first pod that it finds
"get desired number scheduled" logic is copied from `wait_ds_ready`.
=> bugfix: the environment check script should check all pods

chart/templates/daemonset-sa.yaml, chart/values.yaml
This reverts commit 3b64d301eeeffc3a7be1ae33d5ca346a74d816c0.
https://github.com/longhorn/longhorn-manager/pull/938
https://github.com/longhorn/longhorn/issues/2696#issuecomment-863995649
=> Revert "Update chart to allow user to disable-profiler"

chart/questions.yml
Need to reconsider if we can remove the default values in `question.yml` since we already have ones in `values.yaml`
=> chart: Update default tag for instance manager in question.yml

scripts/lhexec
Clean up extra spaces, although these errors are not important, they affect the code specification.
=> Clean up extra spaces

chart/templates/deployment-ui.yaml
Micro PR to fix a typo in Helm chart. UI deployment was using the manager tolerations and nodeselectors.
=> chore: fix wrong values used for ui tolerations and nodeselectors

chart/Chart.yaml
Helm chart doesn't allow `-xxx` as a valid version unless we add `-0` and without prefix `v`.
See helm/helm#9371 for details.
Besides that, the semver parser doesn't allow with prefix `v`.
https://github.com/rancher/rancher/blob/release/v2.5.9/pkg/catalog/manager/manager.go#L218-L221
https://github.com/longhorn/longhorn/issues/2963
=> Helm chart doesn't allow `-xxx` as valid version

chart/templates/storageclass.yaml, chart/values.yaml
This allow Kubernetes to properly changes the volume ownership
and permissions when user specify fsGroup in workload pod
longhorn/longhorn#2964
=> Chart: explicitly set default fsType to EXT4

chart/templates/storageclass.yaml, chart/values.yaml, deploy/longhorn.yaml, examples/storageclass.yaml
This allow Kubernetes to properly changes the volume ownership
and permissions when user specify fsGroup in workload pod
https://github.com/longhorn/longhorn/issues/2964
Signed-off-by: phanle1010 <phan.le@suse.com>
(cherry picked from commit f2856cd358007d9409fdfec5dbcb8094bc085c2f)
=> Explicitly set default fsType to EXT4

chart/Chart.yaml
The maximum supported Kubernetes version of Longhorn v1.1.x is v1.21.x.
https://github.com/longhorn/longhorn/issues/3319
=> Add maximum supported Kubernetes version

chart/templates/crds.yaml
There're 2 settings to control the engine/replica CPU request.
One is the global setting, the unit is the percentage(%).
The other one is per node setting, the unit is the milli CPU.
The max limit applies to the global setting only, which means a maximum of 40% of
total CPU per node.
The global setting will be ignored for a node if the node's
engine/replica on the node is set.
https://github.com/longhorn/longhorn/issues/791
This fixes https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64/500/testReport/junit/tests/test_settings/test_instance_manager_cpu_reservation/
=> Remove maximum limitation for engine/replica CPU request

chart/templates/crds.yaml
Introduce a new field engine.Spec.Active to indicate if the engine is the current one
https://github.com/longhorn/longhorn/issues/3206
=> Improve the way to validate the current engine

chart/Chart.yaml
* Separate Kubernetes version by command  so the chart work in Helm 2
* Also, use "-0" instead of "-r0" to capture pre-releases. See https://github.com/helm/helm/issues/6190
longhorn/longhorn#3356
=> Fixed bug chart cannot be installed with Helm 2

chart/templates/crds.yaml
The field DataSource should be a string with full
information about the source of volume. For example,
snap://vol-name/snapshot-name
longhorn/longhorn#3508
=> Fix bug volume cloning feature is broken

chart/templates/deployment-ui.yaml, chart/values.yaml
This change allows users to specify loadBalancerIP/SourceRanges while for loadBalancer service type in Longhorn-UI service.
=> feat(longhorn-UI): Allow specifying loadBalancer IP/SourceRanges

chart/templates/crds.yaml
Because we should not do any change in the previous version longhorn.io/v1beta1.
We should add the CRD structural schema from longhorn.io/v1beta2.
=> Do not generate schema for longhorn.io/v1beta1 CRD

deploy/prerequisite/longhorn-iscsi-installation.yaml, deploy/prerequisite/longhorn-nfs-installation.yaml
Remove unnecessary permission. The `nsenter` only needs permissions
- `hostPID: true`
- `securityContext.privileged: true`
Longhorn 3549
=> Remove unnecessary permission

chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
https://github.com/longhorn/longhorn/issues/3343
=> Bump backing-image-manager image to v3_20220318

chart/templates/clusterrole.yaml, uninstall/uninstall.yaml
While testing for [#2034](https://github.com/longhorn/longhorn/issues/2034), noticed some webhook RBAC rules are missing.
https://github.com/longhorn/longhorn-manager/commit/ed4a2c4170849fc9fdfd490ff233e6558bf31757
=> Add missing webhook RBAC rule for uninstaller

chart/templates/storageclass.yaml, chart/values.yaml
This PR is related to: https://github.com/longhorn/longhorn/issues/3880 and exposes the storage class "migratable" in the helm chart.
This should help address: https://github.com/harvester/harvester/issues/2088
=> Exposed storage class parameter migratable in the helm chart

chart/templates/storageclass.yaml
Fix the wrong type of parameters in the storage class
Longhorn #3880
(cherry picked from commit f898dec142f1f603e95787dccca86c3e0481ff71)
=> Fix wrong type of parameters in the storage class

chart/templates/serviceaccount.yaml, chart/values.yaml
https://github.com/longhorn/longhorn/issues/3929
=> Allow to add annotations on the serviceAccount managed by the helm chart

chart/templates/daemonset-sa.yaml, chart/values.yaml
As stated above I miss a flag to set logs output format to json which was implemented in longhorn/longhorn-manager#605.
=> Add value to output manager logs to json format

chart/templates/daemonset-sa.yaml, chart/values.yaml
I found that there is no possibility to add those annotations to the Longhorn Manager service via helm-chart:
```
prometheus.io/scrape: 'true'
prometheus.io/port: '9500'
prometheus.io/path: '/metrics'
```
So, here it is.
=> Annotation for service LonghornManager will be configurable.

chart/templates/default-setting.yaml, deploy/longhorn.yaml
Pervious commit will make the `taint-toleration` and `system-managed-components-node-selector` empty in the generated longhorn.yaml if windowsCluster is disabled. It will override the two fields fields with empty values mistakenly during upgrade.
[Longhorn 4289](https://github.com/longhorn/longhorn/issues/4289)
[Longhorn 4246](https://github.com/longhorn/longhorn/pull/4246)
=> chart: fix the conditions of Rancher deployed Windows Cluster

scripts/environment_check.sh
This addition will allow Gentoo users to run this script and get sensible error messages in case they forgot to install required packages.
=> Add Gentoo support to environment_check.sh

enhancements/20220801-failed-backups-cleanup.md
The LEP decribes the design to delete the failed backups by
`backup_volume_controller`.
longhorn/longhorn#3898
Signed-off-by: James Lu <james.lu@suse.com>
=> Failed Backup cleanup LEP

chart/questions.yaml, chart/templates/default-setting.yaml, chart/values.yaml, enhancements/20220801-failed-backups-cleanup.md
Add a new option `failed-backup-ttl` and update the LEP for failed backup cleanup.
longhorn/longhorn#3898
Signed-off-by: James Lu <james.lu@suse.com>
=> Failed backups cleanup: update deploy YAML

chart/questions.yaml, chart/templates/default-setting.yaml, chart/values.yaml, enhancements/20220801-failed-backups-cleanup.md
Add a new option `failed-backup-ttl` and update the LEP for failed backup cleanup.
and modify `Failed Backup cleanup` LEP 
longhorn/longhorn#4469, longhorn/longhorn#3898
Signed-off-by: James Lu <james.lu@suse.com>
=> [BACKPORT][v1.3.x] Failed backups cleanup: update deploy YAML

chart/questions.yml, chart/templates/default-setting.yaml, chart/values.yaml, enhancements/20220801-failed-backups-cleanup.md
Add a new option failed-backup-ttl and update the LEP for failed backup cleanup.
and modify Failed Backup cleanup LEP
https://github.com/longhorn/longhorn/issues/4468, https://github.com/longhorn/longhorn/issues/3898
Signed-off-by: James Lu [james.lu@suse.com](mailto:james.lu@suse.com)
=> [BACKPORT][v1.2.x] Failed backups cleanup: update deploy YAML

deploy/upgrade_responder_server/README.md, deploy/upgrade_responder_server/chart-values.yaml, deploy/upgrade_responder_server/chart.yaml
This is the first step for the pipeline to automatically update the upgrade responder server
longhorn/longhorn#4423
=> Add upgrade responder server helm values

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/improvement_request.md
This reverts commit 6f885bf313c05934704538a7d2f9f462b5464cd0.
Removing the default e2e label from enhancement and improvement issue templates is to avoid creating corresponding test issues directly when they are created/requested by users.
cc @yangchiu
=> Revert "Add require/automation-e2e to enhance/improvement ticket"

chart/questions.yaml, chart/templates/default-setting.yaml, chart/values.yaml
[Longhorn 1711](https://github.com/longhorn/longhorn/issues/1711)
Based on Longhorn-manager [PR#1499](https://github.com/longhorn/longhorn-manager/pull/1499) enhancement to add two arguments in deployment files.
=> Add two arguments for recurring job history

chart/Chart.yaml
[Longhorn 4525](https://github.com/longhorn/longhorn/issues/4525)
=> [Backport v1.3.x] For Longhorn <1.4.0 is restricted to only be installed in the k8s environment below 1.25

chart/Chart.yaml
[Longhorn 4664](https://github.com/longhorn/longhorn/issues/4664)
=> [Backport v1.2.x] For Longhorn <1.4.0 is restricted to only be installed in the k8s environment below 1.25

chart/questions.yaml
=> [BACKPORT][v1.3.2] Fix: update outdated csi-image tags in chart/questions.yaml

chart/questions.yml
=> [BACKPORT][v1.2.6] Fix: update outdated csi-image tags in chart/questions.yaml

chart/templates/uninstall-job.yaml
1. Adding `before-hook-creation` annotation value instruct Helm to remove the previous uninstallation job and before try to avoid the resource conflict https://helm.sh/docs/topics/charts_hooks/#:~:text=Description-,before%2Dhook%2Dcreation,-Delete%20the%20previous
2. Set `restartPolicy: Never` to keep the log of failed uninstallation pod so users can identify the reason that it is failing, see more https://kubernetes.io/docs/concepts/workloads/controllers/job/#:~:text=Note%3A%20If,not%20lost%20inadvertently.
longhorn/longhorn#4711
=> Fix bug: cannot re-run helm uninstall if the first one failed and cannot fetch logs of failed uninstalltion job

chart/Chart.yaml, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml, examples/snapshot/existing_backup.yaml, examples/snapshot/snapshot_existing.yaml, examples/snapshot/snapshot_pvc.yaml, examples/snapshot/snapshotclass.yaml, uninstall/uninstall.yaml
1. Set enablePSP to false by default
1. Bump K8s min version support and CSI sidecar versions 
* Min Kubernetes version from 1.18 to 1.21 
* longhornio/csi-resizer v1.2.0 -> v1.3.0 
* longhornio/csi-snapshotter: v3.0.3 -> v5.0.1
1. Update CSI snapshot examples from v1beta1 to v1
1. Updating images file
1. Gnerating new longhorn.yaml from the chart for kubectl
1. Sync uninstallation manifest from longhorn/longhorn-manager repo
longhorn/longhorn#4003
longhorn/longhorn#4239
=> Kubernetes 1.2.5 support

enhancements/20221123-local-volume.md
[longhorn #3957](longhorn/longhorn#3957)
=> lep: add local-volume

chart/templates/deployment-ui.yaml, chart/values.yaml, deploy/longhorn.yaml
Backport to 1.4.x
Change the number of the replica from 1 to 2 for helm chart and deploy.yaml
https://github.com/longhorn/longhorn/issues/4987
=> [BACKPORT][1.4.x] chore(ui): modify Affinity of UI

chart/templates/deployment-ui.yaml, chart/values.yaml, deploy/longhorn.yaml
Backport to 1.3.x
Change the number of the replica from 1 to 2 for helm chart and deploy.yaml
https://github.com/longhorn/longhorn/issues/4987
=> [BACKPORT][1.3.x] chore(ui): modify Affinity of UI

chart/templates/daemonset-sa.yaml, chart/templates/postupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
Similar to nodeSelector also support affinity.
Signed-off-by: Sjouke de Vries <info@sdvservices.nl>
=> feat(helm): support affinity for longhornManager

chart/questions.yaml
The indentation of chart/questions.yaml in `variable: defaultSettings.restoreVolumeRecurringJobs` is not corrcet.
longhorn/longhorn#5196
=> fix: refine the indentation

chart/questions.yaml
Due to the absence of `Support Bundle Kit` image related variables in `questions.yaml`, users cannot adjust the `Support Bundle Kit` repository name and tags on the Rancher web page.
https://github.com/rancher/charts/pull/2304
https://github.com/rancher/charts/pull/2305
=> fix: add `Support Bundle Kit` image related variables in `questions.yaml`

chart/questions.yaml
Update the supportBundleKit image description as `Longhorn Support Bundle Manager Image`
ref. https://github.com/longhorn/longhorn/pull/5264#discussion_r1067656511
=> fix: update the supportBundleKit image description

scripts/environment_check.sh
Replaced all instances of backtick command substitution with $()-command substitution. 
This also fixes https://github.com/longhorn/longhorn/issues/5304
=> Made environment_check.sh POSIX compliant

chart/templates/deployment-webhook.yaml
=> fix: wrong indentation of priorityClassName in deployment-webhook.yaml

deploy/prerequisite/longhorn-cifs-installation.yaml, deploy/prerequisite/longhorn-iscsi-installation.yaml, deploy/prerequisite/longhorn-nfs-installation.yaml, examples/statefulset.yaml
This PR updates `k8s.gcr.io` to `registry.k8s.io`
Part of https://github.com/kubernetes/k8s.io/issues/4780
=> Update k8s.gcr.io to registry.k8s.io

chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
#5672
We can't move to these versions of external-provisioner and external-snapshotter in Longhorn < v1.5, as they no longer support the v1beta1 VolumeSnapshot API. We deprecated its use in Longhorn v1.4 (https://github.com/longhorn/longhorn/blob/master/CHANGELOG/CHANGELOG-1.4.0.md#deprecation--incompatibilities). I will create separate PRs to bump sidecar versions in the v1.4.x and v1.3.x branches without these components.
We may need a CHANGELOG notice in v1.5 that v1beta1 VolumeSnapshot functionality is completely gone.
EDIT: This comment was previously (incorrectly) missing the "<" sign.
=> Bump CSI sidecars v1.5

chart/questions.yaml
[Longhorn 5794](https://github.com/longhorn/longhorn/issues/5794)
- Fix the upstream to make the group name should be `Longhorn CSI Driver Images` rather than `Longhorn CSI Liveness Probe Images`
https://github.com/longhorn/longhorn/blob/f57838cb7843e3589023e4f035e21b374ffd93f7/chart/questions.yaml#L150
=> fix(chart): fix livenessprobe image group name in question.yaml

examples/network-policy/backing-image-manager-network-policy.yaml, examples/network-policy/instance-manager-networking.yaml
https://github.com/longhorn/longhorn/issues/5651
Although I don't add the egress for the components, the ingress part is updated based on the latest networking doc
=> example: Update network-policy

chart/templates/postupgrade-job.yaml, chart/templates/uninstall-job.yaml
Remove `privileged` requirement from lifecycle jobs `post-upgrade` and `uninstall`.
Ref: longhorn/longhorn#5862
=> fix: remove `privileged` from lifecycle jobs

deploy/prerequisite/longhorn-spdk-setup.yaml
Currently, longhorn uses SPDK AIO feature.
=> prerequisite: set PCI_ALLOWED to none when setting up spdk environment

chart/templates/preupgrade-job.yaml
Correct `pre-upgrade job` pod name.
Ref: longhorn/longhorn#5131, https://github.com/longhorn/longhorn/pull/5567
=> chore: correct pre upgrade pod name

enhancements/20230601-forcibly-activate-a-restoring-dr-volume.md
LEP for activating a DR volume forcibly as long as there is a ready replica even though a DR volume had been activated and stuck in attaching state.
Ref: longhorn/longhorn#1512
=> feat(dr-volume): force activate a DR volume LEP

chart/templates/daemonset-sa.yaml, chart/templates/postupgrade-job.yaml, chart/templates/preupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml, deploy/longhorn.yaml
longhorn/longhorn#5191
For the reason outlined in https://github.com/longhorn/longhorn/issues/5191#issuecomment-1561821738, we decided to hold off on supporting affinity for all Longhorn components, including longhorn-manager. This PR reverts https://github.com/longhorn/longhorn/pull/5168 (plus an additional file longhorn-manager affinity has appeared in since then). Hopefully we can pick this back up again in v1.6.0.
=> Remove longhorn-manager affinity support for now

deploy/prerequisite/longhorn-iscsi-selinux-workaround.yaml
#5627
This is a prerequisite deployment DaemonSet that can apply an SELinux workaround on fully updated RHEL/Rocky systems until `iscsi-initiator-utils` is fixed. It should only be applied if necessary (`container-selinux` is updated and SELinux is enabled).
=> Add iSCSI SELinux workaround for Fedora-like distributions

scripts/environment_check.sh
go-spdk-helper can support nvme-cli v2.0+.
Longhorn/longhorn#5744
=> spdk: nvme-cli should be equal to or greater than 1.12

chart/questions.yaml, chart/templates/default-setting.yaml, chart/values.yaml
#5958 
- Add the StorageReservedPercentageForDefaultDisk configuration to the helm chart.
=> Add reserve storage percentage in helm chart

deploy/upgrade_responder_server/chart-values.yaml, deploy/upgrade_responder_server/chart.yaml
* Release v1.5.1 and v.1.4.3 Longhorn verions
* Increase the CPU and RAM limit for the upgrade responder server:
From the monitoring, sometimes the server is killed by OOM which
leads to some deep decreases in the graphs. As we are getting more
Longhorn nodes now, we should increase the server CPU and RAM
longhorn/longhorn#6274
longhorn/longhorn#6102
=> [upgrade-responder] release v1.5.1 and v.1.4.3 Longhorn verions

.github/workflows/add-to-projects.yml, .github/workflows/create-issue.yml
https://github.com/tspascoal/get-user-teams-membership/blob/master/src/index.js#L57C1-L59C11 `isTeamMember` requires a team variable, so we should just simply check if the reporter is from the org as the original behavior.
=> chore(ghaction): fix invalid member check

deploy/backupstores/cifs-backupstore.yaml
ref: [6530](https://github.com/longhorn/longhorn/issues/6530)
After deploy the manifest, set backuptarget = `cifs://longhorn-test-cifs-svc.default/backupstore` and currently the samba image is using `derekbit/samba:latest`
cc @derekbit
=> add cifs backupstore manifest

chart/README.md, chart/README.md.gotmpl, chart/questions.yaml, chart/values.yaml, scripts/helm-docs.sh
ref: [longhorn/longhorn#5455](https://github.com/longhorn/longhorn/issues/5455)
- use `helm-doc` to generate table of values in readme
- for `default settings`, modify the description in `questions.yaml` of each setting to one sentence.
- make the descriptions in `values.yaml`  same as those  in `questinos.yaml`
- for details, user can check the website
=> doc(chart): add table of helm values

scripts/environment_check.sh
When piping the script to bash (`cat ./environment_check.sh | bash` or `curl` as in https://longhorn.io/docs/1.5.1/deploy/install/#using-the-environment-check-script), the part after `kubectl exec -i` will be interpreted as the input for the command inside kubectl exec command. As the result, the env check script doesn't perform the steps after that kubectl exec command. Removing the `-i` flag fixed the issue. (Thanks @ejweber for the guidance) 
Also, replacing `kubectl exec -t` by `kubectl exec` because the input of kubectl exec command is not a terminal device
longhorn/longhorn#5653
Additional context:
This post has some useful info related to this topic https://stackoverflow.com/questions/30137135/confused-about-docker-t-option-to-allocate-a-pseudo-tty
=> Fix bug: check script fails to perform all checks

.github/workflows/create-issue.yml
Update `.github/workflows/create-issue.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=labels::$LABELS"
```
**TO-BE**
```yaml
echo "labels=$LABELS" >> $GITHUB_OUTPUT
```
=> Replace deprecated command with environment file

chart/templates/preupgrade-job.yaml, chart/values.yaml
fixes: https://github.com/longhorn/longhorn/issues/6415
relates to:  https://github.com/longhorn/charts/pull/126
The preUpgrade job was added in 1.15 and introduces a breaking change for any ArgoCD users when creating a new environment. ArgoCD does not have a method for differentiating between a helm install or a helm upgrade. https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#helm-hooks
Not being able to differentiate between an install or upgrade is not an problem in most cases because hooks are only available to the helm binary. Kubernetes was not built around Helm and hooks are not part of the core kubernetes api. Hooks are at best a makeshift shim. Relying upon hooks introduce undesired complexity when deploying applications and should be avoided because they lack …
=> conditional to disable helm preUpgrade job

chart/ocp-readme.md, chart/values.yaml
OpenShift 4.14 was released into Stable 2023/10/28
REF: 
- https://github.com/okd-project/okd/releases/tag/4.14.0-0.okd-2023-10-28-073550
Pics:
=> OKD / OCP 4.14

chart/templates/network-policies/backing-image-data-source-network-policy.yaml, chart/templates/network-policies/backing-image-manager-network-policy.yaml, chart/templates/network-policies/instance-manager-networking.yaml, chart/templates/network-policies/manager-network-policy.yaml, chart/templates/network-policies/recovery-backend-network-policy.yaml, chart/templates/network-policies/ui-frontend-network-policy.yaml, chart/templates/network-policies/webhook-network-policy.yaml
The Helm chart's network policy objects were all hardcoded to deploy to the `longhorn-system` namespace rather than supporting the user-provided namespace like the rest of the objects.
=> Deploy network policies to the configured namespace

scripts/environment_check.sh
Regarding https://github.com/longhorn/longhorn/issues/6798, environment script no longer need to check `nvme-cil` since instance-manager have `nvme-cil` installed.
=> Remove nvme-cli check

scripts/environment_check.sh
This addresses the issue #7102 - if we fail to get nodes from kubectl, the environment checking script is satisfied that every node in the empty list meets the criteria, and does not fail.
The change checks the return value from kubectl and also that the array of nodes reported is not empty.
=> Add checks for kubectl failure to query nodes.

chart/templates/_helpers.tpl
`namespaceOverride` in value.yaml was removed by https://github.com/longhorn/longhorn/pull/6639
Remove all `namespaceOverride` fields in the chart.
Ref: longhorn/longhorn#6527, https://github.com/longhorn/longhorn/pull/6639
=> fix: remove the namespaceOverride value

chart/README.md, chart/templates/storageclass.yaml, chart/values.yaml
Added the `persistence.nfsOptions` value
- Issue #7351
=> Allow to set NFS mount options for storageclass via values.yaml in helm chart

chart/README.md, chart/templates/daemonset-sa.yaml, chart/templates/preupgrade-job.yaml, chart/values.yaml, deploy/longhorn.yaml
Remove `helmPreUpgradeCheckerJob` and Add `preUpgradeChecker.jobEnabled` and `preUpgradeChecker.upgradeVersionCheck` to allow users to disable pre-upgrade checks or upgrade path enforcement checks.
Update chart/README.md and deploy/longhorn.yaml
Issue longhorn/longhorn#7539
Bypass upgrade path enforcement checks.
=> fix(upgrade): skip upgrade path check

chart/templates/ingress.yaml
Longhorn supports Kubernetes 1.19 as the minimum version, hence Kubernetes version checks for the older versions are not required.
Issue https://github.com/longhorn/longhorn/issues/7601
=> Remove unnecessary Kubernetes version checks in chart manifests

chart/templates/crds.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#7683, longhorn/longhorn#7539
Add a new k8s column `INCOMPATIBLE` for resource `EngineImage`.
=> chore(engineimage): add a new k8s column.

chart/README.md, chart/templates/_helpers.tpl, chart/values.yaml
Issue longhorn/longhorn#6527
This field is used to override the Longhorn namespace when Longhorn is a sub-chart such as a sub-chart of the Harvester.
=> fix(namespace): add the field namespaceOverride back.

chart/templates/daemonset-sa.yaml, chart/templates/services.yaml, deploy/longhorn.yaml
Issue #7399
Remove `sessionAffinity: ClientIP` from Longhorn services. See #7399 for justification.
We could optionally introduce a Helm variable that controls the value of `sessionAffinity` for the Longhorn services that previously used `sessionAffinity: ClientIP`. If we did this, I would argue for making `None` the default, with the option to change back to `ClientIP` if desired. However:
1. I cannot identify any situation in which we should be using `sessionAffinity: ClientIP`,
2. More Helm variables makes Longhorn deployment more difficult to understand.
I'm curious whether reviewers agree.
=> Remove sessionAffinity ClientIP from services

chart/questions.yaml
There are unescaped `"` characters that render the questions.yaml an invalid yaml file
longhorn/longhorn#7496
=> Fix bug invalid questions.yaml file

chart/templates/crds.yaml, deploy/longhorn.yaml
Issue #7425
Adds the CRD fields needed by https://github.com/longhorn/longhorn-manager/pull/2432.
=> Add LastFailedAt and LastHealthyAt replica fields

scripts/environment_check.sh
https://github.com/longhorn/longhorn/issues/7831
Make the environment_check script look for an existing priority class with globalDefault=true to head off potential issues with Longhorn.
This is really only for backport to v1.4.x and v1.5.x. 
In 1.6.0 and later, Longhorn defines its own `longhorn-critical` priority class and ensures that system pods are set to that.
This PR is directly into `v1.5.x` to take the place of [PR 7796](https://github.com/longhorn/longhorn/pull/7796), because it really doesn't need to go into master.
=> fix(environment_check): add check for globalDefault priority class.

chart/templates/crds.yaml, deploy/longhorn.yaml
longhorn/longhorn#7887
Make the InstanceProcessStatus.Conditions CRD field nullable (like the other status CRD fields that are maps). See the linked issue for context.
=> Make InstanceProcessStatus.Conditions nullable

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
longhorn/longhorn#7428
This version of livenessprobe will not allow us to get stuck like in https://github.com/longhorn/longhorn/issues/7116. By upgrading to it, we can revert the changes associated with that ticket.
https://github.com/kubernetes-csi/livenessprobe/issues/236
=> Use livenessprobe version with upstream fix

chart/templates/crds.yaml, deploy/longhorn.yaml
Longhorn 7887
longhorn/longhorn#7887
If Longhorn and Kubernetes are upgraded in a particular order from Longhorn `v1.0.2-` to the latest, `preserveUnknownFields` may remain `true`, even though the default (and intended value) is `false`. As a result, Kubernetes does not consider affected CRDs to have structural schemas, potentially resulting in unexpected behavior (including https://github.com/longhorn/longhorn/issues/7887).
=> Explicitly set preserveUnknownFields to false

chart/templates/storageclass.yaml, deploy/longhorn.yaml
Also ran `./scripts/generate-longhorn-yaml.sh`
Issue https://github.com/longhorn/longhorn/issues/7909
=> Fix `removeSnapshotsDuringFilesystemTrim` not being used in helm chart

scripts/environment_check.sh
Issue https://github.com/longhorn/longhorn/issues/7931
Add a check to environment_check script for kernel version(s) known to cause problems.
This PR addresses one of several sub-tasks in #7931.
=> fix(env_check): Add check for kernel ranges known to have NFS issues.

scripts/restore-backup-to-file.sh
No opened issue
When using `scripts/restore-backup-to-file.sh` script with **cifs** backend, no credentials can be passed to engine container.
This results in error when trying to mount cifs share:
```
time="2024-03-05T14:35:16Z" level=fatal msg="Error running restore to file command" func=cmd.RestoreToFileCmd.func1 file="restore_to_file.go:66" error="cannot mount CIFS share backup/backup, options [soft]: mount failed: exit status 1\nMounting command: mount\nMounting arguments: -t cifs -o soft,<masked>,<masked> //backup/backup /var/lib/longhorn-backupstore-mounts/backup/backup\nOutput: username specified with no parameter\n"
```
As CIFS mounting implemented in `longhorn/backupstore`:
https://github.com/longhorn/backupstore/blob/3a87ee02df77adcf3dda56a64bda196803b1e96b/util/util.go#L353C1-L …
=> fix(scripts): Add CIFS credentials options to restore-backup-to-file

chart/templates/crds.yaml, deploy/longhorn.yaml
longhorn/longhorn#8114
Adds the CRD field required by https://github.com/longhorn/longhorn-manager/pull/2685.
=> Track replica mode transition times with replicaTransitionTimeMap

deploy/upgrade_responder_server/chart-values.yaml, dev/upgrade-responder/install.sh
We also reduced the CPU and memory request/limit because we discovered the root cause of OOMKill is not because of these values being low
longhorn/longhorn#8209
=> Fix a typo and release longhorn v1.6.1 to upgrade responder server

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
longhorn/longhorn#8427
See the linked issue for the upstream context.
=> Bump sidecar container versions for csi-lib-utils issue

chart/README.md, chart/values.yaml
longhorn/longhorn#6313
Make the syntax of the `taintToleration` helm setting more clear, since it can confuse users.
=> Clarify syntax of taintToleration Helm value

chart/templates/clusterrole.yaml, chart/templates/crds.yaml, deploy/longhorn.yaml
Issue # longhorn/longhorn#8070
=> crd: introduce the field `applied` in setting

enhancements/20240423-longhorn-toolbox-cli.md
Issue longhorn/longhorn#7927
This LEP introduces the Longhorn Toolbox CLI, laying the foundation for upcoming development. The CLI aims to streamline manual Longhorn operations like troubleshooting and non-custom-resource operations.
`None`
`None`
=> Feat(LEP): Longhorn toolbox CLI

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
Issue longhorn/longhorn#8623
Update support-bundle image to support node bundle collection timeout.
`None`
- https://github.com/rancher/support-bundle-kit/pull/109
- https://github.com/rancher/support-bundle-kit/releases/tag/v0.0.38
- [longhornio/support-bundle-kit:v0.0.38](https://hub.docker.com/layers/longhornio/support-bundle-kit/v0.0.38/images/sha256-773ce8484b905c4df36c3b68a7614d4f1326888a4c30c761463983e190457199?context=explore)
=> chore(image): update support-bundle-kit to v0.0.38

enhancements/20240314-recurring-and-manual-full-backup-support.md
ref: https://github.com/longhorn/longhorn/issues/7070
Add a proposal of **recurring and manual full backup support**
=> feat(lep): add recurring and manual full backup support

scripts/environment_check.sh
Issue https://github.com/longhorn/longhorn/issues/8697
In case someone is trying Longhorn on a SLES/openSUSE minimal VM image, which includes `kernel-default-base` by default, which does _not_ include `iscsi_tcp`.
With this change applied and `kernel-default-base` installed, we see the following output:
```
[INFO]  Required dependencies 'kubectl jq mktemp sort printf' are installed.
[INFO]  All nodes have unique hostnames.
[INFO]  Waiting for longhorn-environment-check pods to become ready (0/1)...
[INFO]  All longhorn-environment-check pods are ready (1/1).
[INFO]  MountPropagation is enabled
[INFO]  Checking kernel release...
[INFO]  Checking iscsid...
[ERROR] kernel module iscsi_tcp is not enabled on master
[INFO]  Checking multipathd...
[INFO]  Checking packages...
[INFO]  Checking …
```
=> environment_check.sh: add check for iscsi_tcp kernel module

chart/templates/crds.yaml, deploy/longhorn.yaml
In storage-network support for RWX volumes (https://github.com/longhorn/longhorn/issues/8184), Longhorn will proactively delete the workload pod that is using the RWX volumes with the storage network. This action triggers the Kubernetes pod controller to spawn a replacement pod, ensuring the workload ReplicaSet number is fulfilled.
This proposed change is to add the `workloadsStatus.podNamespace` into the Volume CRD, and to be used for the workload pod deletion.
`None`
https://github.com/longhorn/longhorn/pull/8616
=> feat(storage-network): support RWX volumes

chart/templates/crds.yaml, deploy/longhorn.yaml
ref: https://github.com/longhorn/longhorn/issues/2856
Add several fields to support BackingImage enhancement
- HA: minNumberOfCopies
- Scheduling: nodeSelector/diskSelector
- Eviction: evictionRequested.
=> feat(backingimage): add selector and eviction requested fields to backingimage

enhancements/20240402-share-manager-scheduling.md
=> LEP: add "Share Manager Scheduling"

enhancements/20240108-replica-auto-balance-pressured-disks.md
Issue #4105
Propose to enhance replica auto-balance (best-effort) with `replica-auto-balance-disk-pressure-percentage` setting to allow automatically rebuild replica on another disk when the defined threshold is reached.
`None`
`None`
=> feat(lep): auto-balance pressured disks

chart/README.md, chart/questions.yaml, chart/templates/storageclass.yaml, chart/values.yaml
Issue #
Added an option 'defaultDiskSelector' on default storage class to enable the disk selector. 
https://github.com/longhorn/charts/pull/162
=> feat(chart): Added defaultDiskSelector to default storageClass

chart/templates/preupgrade-job.yaml
Issue # longhorn/longhorn#7571
Check if the environment settings are achieved when doing pre-upgrade job with Helm, ref: [environment_check.sh](https://github.com/longhorn/longhorn/blob/master/scripts/environment_check.sh)
=> fix: check environment when doing pre-upgrade with Helm

chart/README.md, chart/templates/servicemonitor.yaml, chart/values.yaml
#8142 
This PR introduces additional settings for ServiceMonitor, primarily focusing on the incorporation of additionalLabels for custom use and annotations. I added another ServiceMonitor settings, that helps to better configure monitoring of Loghorn.
=> feat(serviceMonitor): Add multiple settings for ServiceMonitor resource.

chart/README.md, chart/README.md.gotmpl
This is an addon for longhorn/longhorn#8142 that doesn't affect functionality.
It's weird to have so many metrics/serviceMonitor settings in `Other Settings` instead of in their own group.
=> docs(metrics): move Helm values to a separate section in README.md

chart/README.md, chart/ocp-readme.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml
Issue longhorn/longhorn#8976
Before:
```
longhornio/openshift-origin-oauth-proxy:4.14 (redhat 8.6)
=========================================================
Total: 25 (HIGH: 25, CRITICAL: 0)
┌────────────────────────┬────────────────┬──────────┬────────┬──────────────────────┬──────────────────────┬──────────────────────────────────────────────────────────────┐
│        Library         │ Vulnerability  │ Severity │ Status │  Installed Version   │    Fixed Version     │                            Title                             │
├────────────────────────┼────────────────┼──────────┼────────┼──────────────────────┼──────────────────────┼──────────────────────────────────────────────────────────────┤
│ bind-libs              │ CVE-2023-4408  │ HIGH     │ fixed  │ …
```
=> Fix(cve): update openshift-oauth-proxy to 4.15

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#8976
Fix CVE issues. For:
- csi-attacher
- csi-resizer
- csi-node-driver-registrar
**csi-attacher:**
Before:
```
csi-attacher (gobinary)
=======================
Total: 3 (HIGH: 2, CRITICAL: 1)
┌──────────────────────────────────────────────────────────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬─────────────────────────────────────────────────────────────┐
│                           Library                            │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                            Title                            │
├──────────────────────────────────────────────────────────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼──────────────────────────────────────── …
```
=> Fix(cve): update Kubernetes external components

chart/README.md, chart/questions.yaml, chart/templates/daemonset-sa.yaml, chart/templates/default-setting.yaml, chart/templates/network-policies/recovery-backend-network-policy.yaml, chart/templates/network-policies/webhook-network-policy.yaml, chart/templates/services.yaml, chart/values.yaml, deploy/longhorn-okd.yaml, deploy/longhorn.yaml, examples/network-policy/recovery-backend-network-policy.yaml, examples/network-policy/webhook-network-policy.yaml
…hooks.
Issue #8803 
This customizes the node selector used by the two webhooks to allow individual control of which nodes might be assigned the service, as has been done for RWX HA.  See #6205, for instance.
It now also has the chart documentation for the setting `enable-share-manager-fast-failover`.
This PR **must** be accompanied by https://github.com/longhorn/longhorn-manager/pull/2920 or the webhooks will never be accessible (the endpoint slices will remain empty).
(Now https://github.com/longhorn/longhorn-manager/pull/2811).
=> feat(RWX HA) - add an enabling setting, and make service selectors dynamically settable.

chart/templates/services.yaml, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
ref: https://github.com/longhorn/longhorn/issues/7938
enable csi sidecar metrics on port 8000
- csi-attacher
- csi-provisioner
- csi-resizer
- csi-snapshotter
Add k8s service to allow user to access the metrics through service.
cc @PhanLe1010
=> feat(csi metrics): enable csi sidecar metrics

chart/README.md, chart/values.yaml
longhorn/longhorn#8142
Final description formatting per @jillian-maroket's review of https://github.com/longhorn/website/pull/945.
=> docs(metrics): reformat serviceMonitor Helm variable descriptions

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9172
**longhornio/csi-node-driver-registrar**
Before:
```
longhornio/csi-node-driver-registrar:v2.10.1 (debian 11.9)
==========================================================
csi-node-driver-registrar (gobinary)
====================================
Total: 2 (HIGH: 1, CRITICAL: 1)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                           Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼────────────────────────────────────────────────────────────┤
│ stdlib  │ …
```
=> fix(cve): kubernetes external components

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9172
Fix CVE vulnerabilities.
Before:
```
longhornio/support-bundle-kit:v0.0.40 (suse linux enterprise server 15.6)
Total: 5 (HIGH: 5, CRITICAL: 0)
┌────────────────────────────┬─────────────────────┬──────────┬────────┬────────────────────┬─────────────────────┬───────────────────────────────┐
│          Library           │    Vulnerability    │ Severity │ Status │ Installed Version  │    Fixed Version    │             Title             │
├────────────────────────────┼─────────────────────┼──────────┼────────┼────────────────────┼─────────────────────┼───────────────────────────────┤
│ libopenssl-3-fips-provider │ SUSE-SU-2024:2635-1 │ HIGH     │ fixed  │ 3.1.4-150600.5.7.1 │ …
```
=> fix(cve): update support-bundle-kit to v0.0.41

deploy/prerequisite/longhorn-spdk-setup.yaml
Issue Longhorn/longhorn#9182
According to the [SPDK System Configuration User Guide](https://spdk.io/doc/system_configuration.html), neither uio_pci_generic nor vfio_pci is universally suitable for all devices and environments. Therefore, the preflight installation enables both uio_pci_generic and vfio_pci kernel modules, allowing spdk/setup.sh to automatically select the appropriate module.
=> fix(spdk): enable uio_pci_generic and vfio_pci kernel modules

enhancements/20240522-storage-network-for-rwx-volumes.md
Issue longhorn/longhorn#9223
Update LEP to reflect the fix from https://github.com/longhorn/longhorn/issues/9223.
`None`
`None`
=> fix(lep/storage network for RWX volume): retain custom mounter

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9354
Before:
```
longhornio/csi-node-driver-registrar:v2.11.1 (debian 12.6)
==========================================================
csi-node-driver-registrar (gobinary)
====================================
Total: 1 (HIGH: 0, CRITICAL: 1)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                           Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-24790 │ CRITICAL │ …
```
=> fix(cve): update external components

deploy/upgrade_responder_server/chart-values.yaml
https://github.com/longhorn/longhorn/issues/9347
Called out as necessary by @PhanLe1010 in https://github.com/longhorn/longhorn-manager/pull/3121#issuecomment-2327136164
Also moved entries for `FreezeFilesystemForSnapshot` to keep the list alphabetized, and added some missing `{}`.
Made my best guess as to the capitalization of the setting tag.
=> fix(metrics): add rwx-volume-fast-failover to upgrade responder chart

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9132
Before:
```
longhornio/support-bundle-kit:v0.0.42 (suse linux enterprise server 15.6)
Total: 3 (HIGH: 3, CRITICAL: 0)
┌────────────────────────────┬─────────────────────┬──────────┬────────┬─────────────────────┬─────────────────────┬───────────────────────────────┐
│          Library           │    Vulnerability    │ Severity │ Status │  Installed Version  │    Fixed Version    │             Title             │
├────────────────────────────┼─────────────────────┼──────────┼────────┼─────────────────────┼─────────────────────┼───────────────────────────────┤
│ libopenssl-3-fips-provider │ SUSE-SU-2024:3106-1 │ HIGH     │ fixed  │ 3.1.4-150600.5.10.1 │ 3.1.4-150600.5.15.1 …
```
=> fix(cve): update support-bundle-kit to 0.0.43

chart/README.md, chart/ocp-readme.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
Issue longhorn/longhorn#9132
Fix CVE issues
**After**
```
longhornio/csi-attacher:v4.7.0 (debian 12.6)
============================================
```
```
longhornio/csi-resizer:v1.12.0 (debian 12.6)
============================================
```
```
longhornio/csi-node-driver-registrar:v2.12.0 (debian 12.6)
==========================================================
```
```
longhornio/livenessprobe:v2.14.0 (debian 12.6)
==============================================
```
```
longhornio/openshift-origin-oauth-proxy:4.15 (redhat 9.2)
=========================================================
Total: 12 (HIGH: 12, CRITICAL: 0) …
```
=> fix(cve): update external dependencies

.github/workflows/add-to-projects.yml
Issue Longhorn#9411
- Add a check for teps.is_longhorn_member.outcome == 'success' to prevent errors caused by unrecognized users, such as github-action[bot].
- Move an issue to `New` if it is newly created
- Move an issue to `In Progress` status if a non-longhorn user replies. 
- Move an issue to `Resolved` if a milestone is set
- Move an issue to `Closed` if `wontfix` or `invalid` label is set
=> chore(ci): update status and sprint of community issues if non-longhorn user comments

.github/workflows/update-projects.yaml
=> chore(workflow): fix false alarm in update-projects.yaml

.github/workflows/add-to-projects.yml
=> chore(workflow): add-to-projects doesn't need to handle labeled event

chart/templates/crds.yaml, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
ref: https://github.com/longhorn/longhorn/issues/8757
- store realsize of backingimage in status
- add the realsize to storageScheduled in diskStatus
- add new field scheduledBackingImage in diskStatus
=> feat(crd): add realSize field to backingimage and scheduledBackingImage field to node

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9563
**After:**
```
longhornio/csi-attacher:v4.7.0 (debian 12.6)
============================================
csi-attacher (gobinary)
=======================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ 1.22.5            │ 1.22.7, 1.23.1 │ encoding/gob: …
```
=> fix(cve): csi components

deploy/backupstores/cifs-backupstore.yaml
Issue #9699
cifs in cluster pod crashs on sles15, update the deploy manifest to use new image which include fix https://github.com/derekbit/backupstore-samba/commit/980013dca97703d4543e9b68e5ff888b0e286020 
cc @derekbit 
N/A
N/A
=> chore: update cifs backupstore image

deploy/backupstores/cifs-backupstore.yaml
N/A
For support e2e test case [Test Incremental Restore](https://github.com/longhorn/longhorn-tests/blob/942e57e38ecf62266a449924b3725dfffcbbac36/e2e/tests/regression/test_backup.robot#L63), the default size `4 Gi` is not enough.
After the backup store size increased, test case `Test Incremental Restore` passed on local env using `cifs` backup store
N/A
=> chore: increase cifs in cluster backupstore size from 4096 to 8192

deploy/backupstores/azurite-backupstore.yaml
N/A
The default [Azure CLI ](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)version on SLES 15 is `2.58.0`, and the Azurite container image need updating.
Or below error will appear when using in cluster azurite backup store
```
RESPONSE 400: 400 The API version 2024-08-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry
```
Tested on Sles15 (default azure cli version =`2.58.0`) and on ubuntu 24.04 (default azure cli version =`2.65.0`)
=> chore: update azurite image from 3.30.0 to 3.33.0

enhancements/20240801-delete-backup-in-the-backupstore-asynchronously.md
ref: https://github.com/longhorn/longhorn/issues/8746
Add LEP for backup deletion refactor.
To prevent deletion lock issue from happening, we should disallow backup creation when there is a backup being created.
We refactor the backup deletion flow to make it asynchronous and add a new state `Deleting`
=> feat(LEP): delete backup in the backupstore asynchronously

enhancements/20241028-auto-salvage-support-for-v2-volumes.md
Issue longhorn/longhorn#8430
Proposes extending Longhorn's auto-salvage feature to support v2 volumes
`None`
https://suse.slack.com/archives/C02DR3N5T24/p1713926457976349
=> feat(lep): auto-salvage support for v2 volumes

.github/workflows/wont-fix.yml
Issue https://github.com/longhorn/longhorn/issues/8169
add wont fix label if issues are marked as unplanned
=> ci: add wont fix label if issues are marked as unplanned

.github/workflows/wont-fix.yml
Issue https://github.com/longhorn/longhorn/issues/9611
unset milestone if a backport ticket is closed as not planned
=> ci: unset milestone if a backport ticket is closed as not planned

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9895
Resolves CVE issues.
**After**
```
longhornio/support-bundle-kit:v0.0.47 (suse linux enterprise server 15.6)
```
**Before**
```
longhornio/support-bundle-kit:v0.0.45 (suse linux enterprise server 15.6)
usr/bin/yq (gobinary)
=====================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title …
```
=> chore: update support-bundle to v0.0.47

scripts/environment_check.sh
Issue longhorn/longhorn#9830
Though the node supports NFSv4, the NFS client picks the protocol version by `Defaultvers` defined in `nfsmount.conf`. This may cause problem while using backup-related features.
This change is kind of a backport version of longhorn/cli#129. It is needed since Longhorn v1.6 is still maintained, while `longhornctl check preflight` is provided after v1.7.
=> feat(script/env_check): check overriden NFS version

chart/templates/daemonset-sa.yaml, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue longhorn/longhorn#9830
For Longhorn manager, besides `/etc`, the `/boot` and `/proc` hostpath mounts are needed for environment check, thus we only need RO mount for safety.
Previous change: #9910
Doc change: longhorn/website#1019
=> feat(chart): mount host's /boot & /proc on Longhorn manager for env check

chart/README.md, chart/questions.yaml, chart/values.yaml, deploy/longhorn-images.txt, deploy/longhorn.yaml
Issue longhorn/longhorn#9898
**After**
```
longhornio/support-bundle-kit:v0.0.48 (suse linux enterprise server 15.6)
usr/bin/yq (gobinary)
=====================
Total: 1 (HIGH: 1, CRITICAL: 0)
┌──────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                       Title                       │
├──────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2024-45338 │ HIGH     │ fixed  │ …
```
=> chore(cve): update vendor

chart/README.md, chart/templates/default-resource.yaml, chart/templates/default-setting.yaml, chart/values.yaml, deploy/longhorn-okd.yaml, deploy/longhorn.yaml
Issue # longhorn/longhorn#5411, longhorn/longhorn#10089
Separate the default backup related settings from default settings into a new yaml file `default-backupstore-setting.yaml`
Introduce a new category `defaultBackupStoreSettings` to control the default backupstore related settings with Helm.
=> feat(backup): separate backup settings from default settings

.github/workflows/update-branch-image-tags.yaml
Issue #
```
Commit sha: e93b71f, Author: Longhorn GitHub Bot, Committer: Longhorn GitHub Bot;
Expected "Longhorn GitHub Bot 67932897+longhorn-io-github-bot@users.noreply.github.com",
but got "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>".
```
=> fix(workflow): fix DCO error while executing update-branch-image-tags

.github/workflows/add-issue-to-projects.yml, .github/workflows/periodic-issue-sprint-update.yml, .github/workflows/update-community-review-sprint-issue-status.yaml
Issue Longhorn/longhorn#10410
Set "Ready For Testing" ticket's sprint to current if it is not set.
=> feat(workflow): set Ready For Testing ticket's sprint to current

.github/workflows/create-issue.yml
Issue N/A
fix creating backport issue error: Pagination with the page parameter is not supported for large datasets
=> ci: fix creating backport issue error: Pagination with the page parameter is not supported for large datasets

enhancements/20250331-orphaned-runtime-cleanup.md
Issue #6764 
When a node disconnected or suspended then get back to the cluster, the existed living processes are orphaned. We need a way to identify and clean up these processes.
=> docs(lep): orphaned engine and replica runtime instance cleanup

.github/workflows/create-issue.yml
Issue N/A
fix creating issues error: Pagination with the page parameter is not supported for large datasets
=> ci: fix creating issues error: Pagination with the page parameter is not supported for large datasets

deploy/backupstores/nfs-backupstore.yaml
Issue longhorn/longhorn#10878
Previously, Longhorn did not maintain a repository for the NFS backupstore image build. Now that we've introduced the [longhornio/nfs-backupstore](https://github.com/longhorn/nfs-backupstore), the image name will be aligned with the project name.
=> chore(backupstore/nfs): update to image repo to longhornio/nfs-backupstore

chart/README.md, chart/templates/_helpers.tpl, chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/preupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
Issue #11064
This PR adds the standardized `global.imageRegistry` value, as well as per-image via `$imagePath.registry`, to allow overriding the image.
N/A
See issue for more details.
=> feat(chart): implement standardized image registry override values

chart/README.md, chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/preupgrade-job.yaml, chart/templates/uninstall-job.yaml, chart/values.yaml
Issue #11062
This PR adds the standardized `global.imagePullSecrets` value to set image pull secrets.
N/A
See issue for more details.
=> feat(chart): implement standardized way to specify image pull secrets

deploy/upgrade_responder_server/chart-values.yaml
Server has updated data:
```
➜  ~/.kube curl -d {} https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade | json_pp 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   858  100   856  100     2   4231      9 --:--:-- --:--:-- --:--:--  4268
{
"requestIntervalInMinutes" : 60,
"versions" : [
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.5.5",
"releaseDate" : "2024-04-19T00:00:00Z",
"tags" : [
"stable"
]
},
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.6.4",
"releaseDate" : "2025-01-02T00:00:00Z",
"tags" : [
"stable"
]
},
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.7.3",
"releaseDate" : "2025-02-19T00:00:00Z",
"tags" : [
"stable"
]
},
{
"extraInfo" : …
```
=> feat: release v1.8.2 and v1.9.0 into upgrade responder server

chart/templates/daemonset-sa.yaml, chart/templates/deployment-driver.yaml, chart/templates/deployment-ui.yaml, chart/templates/postupgrade-job.yaml, chart/templates/preupgrade-job.yaml, chart/templates/registry-secret.yaml, chart/templates/uninstall-job.yaml
Issue #11064
In #11063 we originally added some logic to support `global.imagePullSecrets`, but this broke the usage of `privateRegistry.registrySecret`.
We are fixing it in the following way:
* Fix usage of `privateRegistry.registrySecret` when it is a string. This was caused by the `$imagePullSecrets = append ...` line, which was implemented incorrectly.
* If `privateRegistry.registrySecret` is set but not `privateRegistry.createSecret`, no image pull secret will be used for the pods, as this is what is mentioned in the README: "This setting applies only when creation of private registry secrets is enabled."
* If `privateRegistry.registrySecret` is defined but not a string, an error is thrown. This is because the template currently expects it to be a string.
See the original issue.
=> fix(chart): fix usage of privateRegistry.registrySecret

.github/workflows/create-issue.yml
Issue Longhorn/longhorn#11283
Should reopen backport ticket if it is existing after adding backport/<version> label back.
=> fix(workflow): reopen backport ticket if it is existing

enhancements/20250701-configurable-backup-block-size.md
Issue #5215
Propose a design, to make the backup block size configurable. A larger backup block size may boost the transmission performance, and reduce the potential request cost for backup targets like S3. This design doc includes some comparison between the different backup block sizes.
=> docs(lep): configurable backup block size

.github/workflows/update-longhorn-issue.yml
Issue #
Sprint should be set by developer
=> fix(workflow): no need to set Sprint if ticket is labeled, milestoned, and so on
