deploy/example.yaml
examples/example.yaml
examples/example_pv.yaml
examples/pvc.yaml

Match longhorn-manager: 7db0d8bd7a69bdfc0bf1a299f3929448aff977d3
Mostly bug fixes and clean up.

Update longhorn-manager and UI

---

deploy/longhorn-gke.yaml
deploy/longhorn.yaml

Update longhorn-manager image to rancher/longhorn-manager:1ebf5cb

---

README.md

Longhorn Manager:
image: rancher/longhorn-manager:1ebf5cb
version: https://github.com/rancher/longhorn-engine/tree/8be099b76eb5acdbdcf2a7bcfffd6ce096884041
Longhorn Engine:
image: rancher/longhorn-engine:de88734
version: https://github.com/rancher/longhorn-engine/tree/8be099b76eb5acdbdcf2a7bcfffd6ce096884041
Longhorn UI:
image: rancher/longhorn-ui:4611040
version: https://github.com/rancher/longhorn-ui/tree/46110405960c25722b3e479ca96dd6f1d5e7ab5f

Longhorn v0.2 release

---

deploy/longhorn-gke.yaml
deploy/longhorn.yaml

Manager commit ae53e68957477860efb917a22ad3d7f72af15a50

Update maager to rancher/longhorn-manager:010fe60

---

deploy/uninstall-for-upgrade.yaml

Would be used for the upgrade steps to v0.3.

Add uninstall-for-upgrade.yaml

---

deploy/longhorn.yaml

Manager commit:
commit 34bac041a58b1086361f6d7d653fcd9954ff104b
Author: Sheng Yang <sheng@yasker.org>
Date:   Wed Aug 8 01:09:34 2018 -0700
Update image
Manager to rancher/longhorn-manager:9838a5f
UI to rancher/longhorn-ui:99252cc

Sync with Longhorn Manager

---

README.md
docs/upgrade.md

This reverts commit ac838a35a96a2059fb2dfcd91e450d8511f4833f.
Adding back the doc. We're going to release when it's ready.

Revert "docs: Remove Upgrade instruction for now"

---

docs/multidisk.md

Fixed issue: https://github.com/rancher/longhorn/issues/219

Update default reserved value for root disk

---

deploy/uninstall-for-upgrade.yaml

https://github.com/rancher/longhorn/issues/208
@yasker We should create a `v0.1` branch and rebase this PR.

Add uninstall yaml for v0.1

---

deploy/longhorn.yaml

Sync with manager:
commit 3b86e81b2157a4457daaef10871bfae78356ae18
Author: Sheng Yang <sheng@yasker.org>
Date:   Tue Aug 21 23:09:11 2018 -0700
Update image to rancher/longhorn-manager:v0.3-rc5
Engine image: rancher/longhorn-engine:v0.3-rc5
UI Image: rancher/longhorn-ui:v0.3-rc5

Longhorn v0.3-rc5

---

docs/chart.md

https://github.com/rancher/longhorn/issues/261

Document Longhorn chart

---

deploy/longhorn.yaml

commit 720a3c0d469ecae96908f8410a170995df059ab5
Author: Sheng Yang <sheng@yasker.org>
Date:   Mon Sep 17 18:44:37 2018 -0700
Longhorn v0.3.1 release
Pin down engine version to v0.3.0

Sync with manager

---

docs/chart.md

Support Rancher v2.0.x users

---

README.md
deploy/uninstall.yaml
docs/chart.md

https://github.com/rancher/longhorn/issues/337

Update uninstallation procedure, synchronize chart doc

---

README.md
docs/k8s-workload.md

https://github.com/rancher/longhorn/issues/536

Add doc for Kubernetes integration feature

---

README.md
docs/dr-volume.md

https://github.com/rancher/longhorn/issues/535

Add doc for disaster recovery volume

---

README.md

There is a needless symbol ``` ` ``` in README.md which should be delete.

del needless symbol

---

chart/questions.yml
chart/templates/clusterrole.yaml
chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/623

chart: Update chart for customized default settings

---

MAINTAINERS
README.md

Add community section in the README.md

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/584

chart: Update chart for customized taint toleration setting

---

README.md
docs/customized-default-setting.md
docs/settings.md
docs/storage-tags.md
docs/taint-toleration.md
docs/troubleshooting.md

docs: Add documents for v0.6.0

---

chart/templates/clusterrole.yaml
chart/templates/clusterrolebinding.yaml
chart/templates/daemonset-sa.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml

https://github.com/longhorn/longhorn/issues/742

chart: Update to use appsV1 API

---

dev/scripts/lm-update.sh

dev: Add lm-update.sh script

---

docs/csi-config.md

doc: Update the doc for k3s v0.10.0+ support

---

README.md
docs/restore-volume.md

doc: Restore volume after unexpected detachment

---

chart/Chart.yaml

chart: Update the logo

---

docs/upgrade-from-v0.6.2-to-v0.7.0.md
docs/upgrade.md

Add upgrade steps draft for v0.7.0

---

chart/README.md
chart/questions.yml
chart/templates/deployment-driver.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/358

chart: Remove flexvolume

---

README.md
docs/recover-volume.md

Rename `restore-volume.md` to `recover-volume.md`

---

.github/stale.yml

Enable GitHub stale bot

---

docs/upgrade-from-v0.6.2-to-v0.7.0.md

- fix 'apply' command, needs `-f`
- update anchor tag, add some context to the link. This makes it readable without having to click.
Signed-off-by: ted <ted@timmons.me>

update the update-to-070 documentation

---

README.md
docs/expansion.md

https://github.com/longhorn/longhorn/issues/17

doc: Add doc for volume expansion feature

---

docs/expansion.md

https://github.com/longhorn/longhorn/issues/17

doc: Update expansion.doc for revert case

---

docs/recover-volume.md

doc: Update doc for the remount feature

---

docs/node-failure.md

doc: Improve node failure doc

---

chart/templates/postupgrade-job.yaml

https://github.com/longhorn/longhorn/issues/1057
this allows to recover a failed installation / upgrade

delete existing hook

---

README.md
chart/templates/deployment-ui.yaml
chart/values.yaml
docs/longhorn-ingress.md

Chart: change frontend service to type ClusterIP

---

README.md

Add EKS instructions for open-iscsi

---

README.md

Signed-off-by: Tom Paine <github@aioue.net>

Add document for Helm3

---

docs/expansion.md

doc: Update expansion.md

---

docs/longhorn-ingress.md

add AWS EKS ELB instructions for nginx ingress

---

README.md

Update README.md for v0.8.0

---

chart/questions.yml
docs/customized-default-setting.md
docs/multidisk.md
docs/settings.md

Update default data path to /var/lib/longhorn

---

enhancements/YYYYMMDD-template.md

Add enhancements proposal document template

---

enhancements/20200319-default-disks-and-node-configuration.md

longhorn/longhorn#991
longhorn/longhorn#1053

enhancements: Add design doc default-disk-and-node-tag-setup

---

enhancements/YYYYMMDD-template.md

enhancement: Update template

---

README.md
chart/questions.yml
chart/templates/_helpers.tpl
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml
chart/templates/postupgrade-job.yaml
chart/templates/registry-secret.yml
chart/templates/uninstall-job.yaml
chart/values.yaml
docs/longhorn-airgap.md

Add airgap chart install and install docs

---

docs/longhorn-airgap.md

update longhorn airgap docs

---

chart/Chart.yaml
chart/app-readme.md
docs/chart.md
docs/csi-config.md
docs/driver.md
docs/restore-to-file.md
docs/restore_statefulset.md
docs/snapshot-backup.md
docs/upgrade.md
examples/restore_to_file.yaml.template

Update longhorn docs

---

enhancements/20200331-replace-filesystem-id-key-in-disk-map.md

https://github.com/longhorn/longhorn/issues/972

enhancement: replace filesystem ID key in Disk map

---

enhancements/20200331-replace-filesystem-id-key-in-disk-map.md
enhancements/YYYYMMDD-template.md

enhancement: Add `API Changes` in the template

---

chart/questions.yml

add Longhorn and CSI use default image question

---

chart/questions.yml

https://github.com/longhorn/longhorn/issues/1308
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>
Longhorn Default Settings: False
Longhorn Default Settings: True

Hide the customized default setting by default in Rancher chart

---

chart/questions.yml

longhorn/longhorn#1308
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

fix typo in chart questions

---

chart/questions.yml

Fix Instance Manager Image Tag Chart Label

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

chart: Update settings

---

chart/README.md
chart/app-readme.md

rancher/rancher#27423
longhorn/longhorn#1454

chart: Add downgrade warning and highlight namespace requirement

---

chart/questions.yml

This PR updates questions.yml for v1.0.1-rc1 of the chart to include a question for populating the initial value of the new Priority Class setting.

Update questions.yml for v1.0.1-rc1

---

chart/Chart.yaml
chart/values.yaml

Correct chart tags to v1.0.1-rc3

---

.gitignore
dev/scale-test/.gitignore
dev/scale-test/README.md
dev/scale-test/sample.sh
dev/scale-test/scale-test.py
dev/scale-test/statefulset.yaml

scale-test.py is currently a work in progress and needs some additional
implementation for the data processing and analysis part.

Add scale test scripts

---

chart/templates/daemonset-sa.yaml

this fix related issue with containerd
https://github.com/containerd/containerd/issues/3667

/var/run/ - mountPropagation: Bidirectional

---

enhancements/20200721-refactor-restore-for-rebuild-enabling.md

enhancement: Add LEP 'Refactor restore for rebuild enabling'

---

enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md

https://github.com/longhorn/longhorn/issues/298

Add replica eviction support for disks and nodes enhancement document

---

enhancements/20200817-improve-node-failure-handling.md

enhancements: add improve node failure handling enhancement document

---

enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md

This commit is for supporting eviction for detached volume.
https://github.com/longhorn/longhorn/issues/1704

Update replica evcition support for disks and nodes enhancement document

---

enhancements/20200904-csi-snapshot-support.md

Add LEP for csi snapshot support

---

enhancements/20200904-csi-snapshot-support.md

Add note about `VolumeSnapshotClass` to csi snapshot LEP

---

enhancements/20200821-add-revision-counter-disable-support.md

https://github.com/longhorn/longhorn/issues/508

Add replace revision counter in longhorn engine enhancement document

---

enhancements/20201002-allow-recurring-backup-detached-volumes.md

add enhancement document for the feature `allow recurring backup for detached volumes`

---

deploy/backupstores/nfs-backupstore.yaml

https://github.com/longhorn/longhorn/issues/6

Update nfs backupstore image

---

chart/templates/storageclass.yaml
chart/values.yaml

Add recurringJobs to StorageClass

---

deploy/backupstores/minio-backupstore.yaml

https://github.com/longhorn/longhorn/issues/6

Update minio backupstore image to support amd64 and arm64

---

enhancements/20201020-recover-from-volume-failure-by-delete-and-recreate-the-workload-pod.md

add LEP for feature `handling volume remount by killing the consuming pod`

---

chart/README.md

https://github.com/longhorn/longhorn/issues/1617

Update longhorn chart README.md

---

README.md
chart/README.md

While looking at the code, I noticed some spelling and grammatical mistakes in the main README and the chart directory's README, so I tried to fix them to the best of my ability.
I hope this can be useful

Fixes for some grammatical errors and misspellings in some of the READMEs

---

deploy/iscsi/longhorn-iscsi-installation.yaml

Add iscsi installation yaml file to provide a convenient way to install
iscsi on every host.
https://github.com/longhorn/longhorn/issues/1741

Add iscsi installtion daemonset yaml file

---

enhancements/20200821-rebuild-replica-with-existing-data.md

enhancements: Add LEP 'Rebuild replica with existing data'

---

enhancements/20200909-prometheus-support.md

Issues:
longhorn/longhorn#1180
longhorn/longhorn#1832

enhancement: Add LEP for Prometheus support

---

enhancements/20201106-disk-reconnection.md

enhancement: Add a new enhancement 'disk-reconnection'

---

chart/questions.yml
chart/templates/clusterrole.yaml
chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/2043

Chart: Add share manager and update instance manager image tag

---

chart/questions.yml

chart: Correct the inconsistent for question.yml

---

chart/Chart.yaml
chart/README.md

Chart: Add share manager info

---

README.md

Longhorn v1.1.0 release

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

chart: add concurrent-automatic-engine-upgrade-per-node-limit setting

---

enhancements/20210111-upgrade-engine-automatically.md

Add LEP for feature automatically upgrade engine for volumes

---

enhancements/20201220-rwx-volume-support.md

longhorn/longhorn#1470
longhorn/longhorn#2149

Add LEP for rwx feature

---

chart/questions.yml
chart/templates/clusterrole.yaml
chart/templates/default-setting.yaml
chart/values.yaml

chart: Update chart for the backing image feature

---

enhancements/20201228-enable-backing-image.md

enhancement: Add a new enhancement 'enable backing image'

---

enhancements/20210216-volume-live-migration.md

Add LEP for live migration feature

---

enhancements/20210125-enhanced-cpu-reservation.md

enhancement: Add a new LEP 'enhanced-cpu-reservation'

---

chart/templates/crds.yaml

chart: Add missed CRD BackingImage

---

chart/README.md

Update chart README

---

.github/stale.yml

Update the exempt labels

---

chart/templates/daemonset-sa.yaml
chart/values.yaml

Add annotations to longhorn-manager DaemonSet template to support add annotations to the longhorn-manager Pods.
https://github.com/longhorn/longhorn/issues/2387

Add annotations to longhorn manager DaemonSet

---

.github/ISSUE_TEMPLATE/bug_report.md

Add installation method in the bug template

---

chart/values.yaml

Updates wording according to the comment https://github.com/longhorn/longhorn/issues/2387#issuecomment-808469012

Updates wording to specify the annotations only added to longhorn-manager Pods

---

enhancements/20210216-volume-live-migration.md

Fix missing nil declaration in live migration example

---

chart/questions.yml
chart/templates/clusterrole.yaml
chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
chart/values.yaml

chart: Update chart for the enhanced backing image feature

---

chart/templates/crds.yaml

chart: Show state in the print columns for backing image manager CR

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt
uninstall/uninstall.yaml

Update version to v1.1.1-rc1

---

enhancements/20200727-add-replica-eviction-support-for-disks-and-nodes.md
enhancements/20200821-add-revision-counter-disable-support.md
enhancements/20210111-upgrade-engine-automatically.md

correct several wrong words

---

enhancements/20210510-automatic-rebalance-replica.md

https://github.com/longhorn/longhorn/issues/587

Add LEP - automatic rebalance replica

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/587

Update chart to support replica auto balance

---

chart/README.md

https://github.com/longhorn/longhorn/issues/2573

Add bash to install requirement

---

chart/templates/daemonset-sa.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/2696

Update chart to allow user to disable-profiler

---

chart/templates/daemonset-sa.yaml
chart/values.yaml

Backport https://github.com/longhorn/longhorn/pull/2700
https://github.com/longhorn/longhorn/issues/2696

[Backport] [v1.1.2] update chart for manager pprof option

---

chart/templates/daemonset-sa.yaml
chart/values.yaml

This reverts commit 95ed73d356870d2fc19ad4d96dd5dd7fb0613374.
https://github.com/longhorn/longhorn-manager/pull/938
https://github.com/longhorn/longhorn/issues/2696#issuecomment-863995649

Revert "Update chart to allow user to disable-profiler"

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

Update to v1.1.2

---

README.md

Update latest release version

---

enhancements/2021.07.26-pv-encryption.md

longhorn/longhorn#1859
Still need to implement additional extension, which can be indepentendly added once the base PR for https://github.com/longhorn/longhorn-manager/pull/964 is merged.
- [RWX encryption support]() // TODO: create issue
- [Expansion support](https://github.com/longhorn/longhorn/issues/2794)
- [Restore support]() // TODO: create issue
- [VolumeMode Block support]() // TODO: create issue

Add LEP for PV encryption support

---

enhancements/20210525-async-pull-backups.md

[LEP] Asynchronous pull backup volumes into cluster CR

---

enhancements/20210624-label-driven-recurring-job.md

https://github.com/longhorn/longhorn/issues/467

Add LEP - label-driven recurring job

---

enhancements/20210810-volume-clone.md

Add LEP for CSI volume cloning

---

chart/questions.yml
chart/templates/clusterrole.yaml
chart/templates/crds.yaml
chart/templates/storageclass.yaml
chart/values.yaml
deploy/longhorn.yaml
examples/storageclass.yaml
uninstall/uninstall.yaml

https://github.com/longhorn/longhorn/issues/467

Update chart and YAML for Label driven recurring job

---

chart/questions.yml

https://cloud-native.slack.com/archives/CNVPEL9U3/p1629250829158500

chart: Explicit explain how Longhorn identifies a node zone in questions.yml

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

Sync chart files from 1.1.2

---

chart/Chart.yaml

Raise minimum kubernetes version to v1.18.0 in ./chart/Chart.yaml

---

chart/templates/crds.yaml

https://github.com/longhorn/longhorn-manager/pull/1005/files#issuecomment-905201799

Show backup state

---

chart/questions.yml

Update CSI images in questions.yml

---

chart/Chart.yaml
chart/README.md
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update to v1.2.0

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

chart: Add new setting 'Backing Image Recovery Wait Interval'

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt

Update share-manager image to v1_20210914

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt

Backport update SM image to v1_20210914 for v1.2.1

---

chart/questions.yml
chart/templates/default-setting.yaml
chart/values.yaml

chart: Add new setting 'Concurrent Replica Rebuild Per Node Limit'

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
scripts/lhexec
uninstall/uninstall.yaml

Update to 1.2.1-rc1

---

chart/questions.yml

chart: Update setting 'ConcurrentReplicaRebuildPerNodeLimit'

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update to 1.2.1-rc2

---

examples/network-policy/backing-image-data-source-network-policy.yaml
examples/network-policy/backing-image-manager-network-policy.yaml
examples/network-policy/instance-manager-networking.yaml
examples/network-policy/manager-network-policy.yaml
examples/network-policy/ui-network-policy.yaml

Add network policy examples

---

.github/workflows/stale.yml

Add workflow_dispatch event for stale action

---

.github/workflows/stale.yml

Exempt all PRs/Issues w/ assignees

---

.github/workflows/stale.yml

Make the stale action reusable

---

chart/values.yaml
deploy/longhorn-images.txt

Change the CSI sidecar images from upstream repo to Longhorn repo

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Share-manager image update to support fs expansion
longhorn/longhorn#2868

v1.2.3 - 2868-sm-image-fs-expansion

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

v1.3 - 2868-sm-image-fs-expansion

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt
uninstall/uninstall.yaml

Update to 1.1.3-rc1

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt
uninstall/uninstall.yaml

https://github.com/longhorn/longhorn-manager/commit/48728f0d2d89b52987da90a0a2f29630362bb263

Update instance manager version

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/improvement_request.md
.github/ISSUE_TEMPLATE/question.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/test.md

Update issue templates

---

chart/templates/crds.yaml

- Copy the CRD yaml manifest from longhorn-manager
- Manually add the `{{- include "longhorn.labels" . | nindent 4 }}` after `metadata.labels`.
Longhorn 791

Update CRD with structural schema

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt

Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

patch longhorn backing image and share manager images

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update to 1.2.3-rc1

---

chart/questions.yml

ref: https://github.com/longhorn/longhorn/commit/7f5c7e05a59e306be7bb89dcb1dbef5231ed1ae6

Update csi images based on longhornio

---

chart/templates/services.yaml

Add headless services for instance manager pods

---

enhancements/20210726-pv-encryption.md

Update the storage class parameter.
And I thought same name of secret aligned with the above storage class example will make more sense. :) 
Signed-off-by: Khushboo <fnu.khushboo@suse.com>

change secret name to align with storage class name

---

README.md

Add release type

---

chart/templates/crds.yaml

Update CRD with v1beta1 and v1beta2

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update im to v1_20211210

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
deploy/release-images.txt
uninstall/uninstall.yaml

Update to v1.1.3-rc3

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update to v1.2.3-rc2

---

chart/templates/crds.yaml

Update CRD with nullable fields

---

chart/Chart.yaml
chart/questions.yml
chart/templates/services.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
examples/network-policy/backing-image-data-source-network-policy.yaml
examples/network-policy/backing-image-manager-network-policy.yaml
examples/network-policy/instance-manager-networking.yaml
examples/network-policy/manager-network-policy.yaml
examples/network-policy/ui-network-policy.yaml
uninstall/uninstall.yaml

Merge release 1.2.3 change to master

---

chart/templates/services.yaml

https://github.com/longhorn/longhorn/issues/3433
Signed-off-by: Lukas Auerbeck <lauerbeck@gmx.at>

Make namespace configureable for services

---

chart/templates/services.yaml

Signed-off-by: Lukas Auerbeck <lauerbeck@gmx.at>
Backport #3453

[BACKPORT] Make namespace configureable for services

---

chart/questions.yaml

Signed-off-by: damiendawreck <d.pc@live.nl>

Fix repica typo

---

chart/templates/crds.yaml

chart: add recurring job retain count max check

---

examples/network-policy/webhook-network-policy.yaml

example: add longhorn webhook network policy yaml manifest

---

enhancements/20220110-extend-csi-snapshot-to-support-longhorn-snapshot.md

Add LEP for feature Extend CSI Snapshot support to Longhorn snapshot

---

chart/templates/crds.yaml

Add //+nullable to engine status fields
Longhorn 3538

Add //+nullable to engine status fields

---

chart/questions.yaml
chart/values.yaml

Add config value for ingress path
by setting `ingress.path` you can specify the default ingress path for longhorn

Add config value for ingress path

---

deploy/prerequisite/longhorn-nfs-installation.yaml

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

chore : enable nfs kernel module

---

README.md

Give a note about the master for development

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Use an instance manager version with the tgt 100% CPU usage fix.
https://github.com/longhorn/longhorn/issues/3636
Signed-off-by: Keith Lucas <keith.lucas@suse.com>

Update instance manager

---

chart/questions.yaml
chart/templates/storageclass.yaml
chart/values.yaml

Adopt feature from https://github.com/longhorn/longhorn/issues/1045 for helm charts.
Kind thanks to @jenting leading me here.

introducing storage class locality

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/backupstores/minio-backupstore.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.4-rc1

---

chart/templates/crds.yaml
chart/templates/services.yaml

charts: add conversion to crds

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update dev versions to components and chart for the master branch

---

chart/templates/deployment-webhook.yaml

chart: set securityContext of webhook

---

deploy/longhorn.yaml
deploy/prerequisite/longhorn-iscsi-installation.yaml
deploy/prerequisite/longhorn-nfs-installation.yaml
scripts/generate-longhorm-yaml.sh

ref: https://github.com/longhorn/longhorn/issues/3716

Generate longhorn.yaml based on chart

---

chart/templates/crds.yaml
chart/templates/deployment-webhook.yaml

chart: update webhook and crd manifests

---

chart/Chart.yaml
chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.4

---

uninstall/uninstall.yaml

(cherry picked from commit 9a36732ebd68b3c4800f45cb5291324e10c7c99c)

Change imagePullPolicy of uninstall job to IfNotPresent

---

enhancements/20220317-snapshot-prune.md

Add LEP 'Snapshot Prune'

---

enhancements/20220317-snapshot-prune.md

#3613
To address comment https://github.com/longhorn/longhorn/pull/3754#pullrequestreview-914758745

Update LEP 'Snapshot Prune'

---

examples/data_migration.yaml

https://github.com/longhorn/longhorn/issues/3787

Fix data migration YAML command args

---

chart/templates/deployment-ui.yaml
deploy/longhorn.yaml

Longhorn 3829
https://github.com/longhorn/longhorn/issues/3829
Signed-off-by: Siye Wang <siye@rancher.com>

[master] Make Longhorn UI Listen Binding configurable

---

enhancements/20220408-support-kubernetes-ca.md

https://github.com/longhorn/longhorn/issues/2203

Add LEP - Support K8s Cluster Autoscaler

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/2203

Update deployment for cluster autoscaler support

---

chart/questions.yaml
chart/templates/clusterrole.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml

orphaned data cleanup: update deploy YAML

---

chart/templates/storageclass.yaml

[Longhorn #3880](https://github.com/longhorn/longhorn/issues/3880)

Fix wrong type of parameters in the storage class

---

chart/questions.yaml
chart/templates/daemonset-sa.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

longhorn/longhorn#3839
longhorn/longhorn#3922

Update chart + deployment to add MTLS support

---

enhancements/20220428-storage-network-through-grpc-proxy.md

https://github.com/longhorn/longhorn/issues/2285
https://github.com/longhorn/longhorn/issues/3546

Add LEP for Storage Network Through gRPC Proxy

---

chart/questions.yaml

Fix incorrect indent and missing double-quote in questions.yaml

Fix incorrect indent and missing double-quote in questions.yaml

---

.gitignore
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update im image to v1_20220512 (non tls cli fix)

---

chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
deploy/longhorn.yaml

[Longhorn 2570](https://github.com/longhorn/longhorn/issues/2570)

Fix customize default settings while upgrade/update

---

chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
deploy/longhorn.yaml

We will move the logic to configmap controller.
https://github.com/longhorn/longhorn/issues/2570

Revert ConfigMap to Setting Design

---

chart/templates/clusterrole.yaml
chart/templates/crds.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

Update charts for Longhorn snapshot CRDs

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.0-rc1

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4004
https://github.com/longhorn/longhorn/issues/3546

grpc-proxy: add proxyApiMinVersion to deployement

---

chart/templates/daemonset-sa.yaml
deploy/longhorn.yaml

[Longhorn 2570](https://github.com/longhorn/longhorn/issues/2570)

Remove longhorn-default-settings from manifests

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Fix bug nullable field is empty in snapshots.spec.label

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Bump CSI images and share manager image tags

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/3546

version-bump: instance-manager

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

longhorn/longhorn#4035
Signed-off-by: James Lu <james.lu@suse.com>

Update longhorn-shared-manager image

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Longhorn/longhorn#3155
Longhorn/longhorn#3970

Update CRDs after backing image refactoring

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.0-rc2

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn.yaml

Update longhorn-instance-manager to v1_20220602

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4076

version-bump: instance-manager to v1_20220607

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.0-rc3

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4096

version-bump: longhorn-instance-manager

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn-instance-manager/pull/125#issuecomment-1152819768

version-bump: instance-manager to v1_20220611

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.0

---

deploy/longhorn.yaml

Release 1.3.0 update deploy.yaml

---

scripts/environment_check.sh

Signed-off-by: Dante Foulke <flkdnt@gmail.com>

bugfix for issue #4216

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4136
https://github.com/longhorn/longhorn/issues/4265

Update longhorn-instance-manager to v1_20220722

---

chart/questions.yaml
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml
chart/templates/deployment-webhook.yaml
chart/templates/postupgrade-job.yaml
chart/templates/storageclass.yaml
chart/templates/uninstall-job.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/4246

chart: support Rancher deployed Windows Cluster

---

chart/questions.yaml
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml
chart/templates/deployment-webhook.yaml
chart/templates/postupgrade-job.yaml
chart/templates/storageclass.yaml
chart/templates/uninstall-job.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/4274
https://github.com/longhorn/longhorn/issues/4246

[BACKPORT][v1.3.x] chart: support Rancher deployed Windows Cluster

---

chart/questions.yml
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml
chart/templates/postupgrade-job.yaml
chart/templates/storageclass.yaml
chart/templates/uninstall-job.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/4273
https://github.com/longhorn/longhorn/issues/4246

[BACKPORT][v1.2.x] chart: support Rancher deployed Windows Cluster

---

chart/templates/crds.yaml

Signed-off-by: Tristan Lins <tristan.lins@chamaeleon.de>

[v1.3.x] Add `preserveUnknownFields: false` to crd specs

---

chart/templates/default-setting.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4290
https://github.com/longhorn/longhorn/issues/4289

[BACKPORT][v1.3.1] chart: fix the conditions of Rancher deployed Windows Cluster

---

chart/templates/default-setting.yaml

https://github.com/longhorn/longhorn/issues/4289
https://github.com/longhorn/longhorn/issues/4291

[BACKPORT][v1.2.5] chart: fix the conditions of Rancher deployed Windows Cluster

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.1 RC1

---

.github/workflows/add-to-projects.yaml
.github/workflows/stale.yaml

Add community issues to Community project

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4338

[BACKPORT][v1.3.1] Update charts

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4332
https://github.com/longhorn/longhorn/issues/4339

[BACKPORT][v1.2.5] Update charts

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

To refresh installed packages in the image.

Update share and backing images

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.1 RC2

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.1

---

uninstall/uninstall.yaml

[BACKPORT][v1.2.x] Add volumeattachment to uninstaller's service account

---

uninstall/uninstall.yaml

[BACKPORT][v1.3.x] Add volumeattachment to uninstaller's service account

---

uninstall/uninstall.yaml

Add volumeattachment to uninstaller's service account

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
scripts/environment_check.sh
uninstall/uninstall.yaml

Release 1.2.5-rc1

---

scripts/environment_check.sh

https://github.com/longhorn/longhorn/issues/4472

[BACKPORT][v1.2.x] environment_check.sh

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement_request.md

Add require/automation-e2e to enhance/improvement ticket

---

enhancements/YYYYMMDD-template.md

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

fix: enhancement template typos

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update managed components images

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.5 RC2

---

scripts/longhorn_rancher_chart_migration.sh

There shouldn't have the = character
longhorn/longhorn#3714

Fix the document about the flags

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.5

---

chart/questions.yaml
chart/templates/deployment-recovery-backend.yaml
chart/templates/services.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/2293
Signed-off-by: Derek Su [derek.su@suse.com](mailto:derek.su@suse.com)

chart: add and update manifests for recovery-backend

---

.github/workflows/close-issue.yml
.github/workflows/create-issue.yml

ci: add github action for backport and automation issues
For https://github.com/longhorn/longhorn/issues/4159

ci: add github action for backport and automation issues

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

[Longhorn 2380](https://github.com/longhorn/longhorn/issues/2380)

Update longhorn-share-manager to v1_20220914

---

.github/workflows/create-issue.yml

ci: add kind/backport label for backport issues

ci: add kind/backport label for backport issues

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

[Longhorn 3601](https://github.com/longhorn/longhorn/issues/3601)

deploy: update longhorn-instance-manager to v1_20220920

---

.github/workflows/create-issue.yml

ci: refine automation issue action

ci: refine automation issue action

---

chart/values.yaml

[Longhorn 4601](https://github.com/longhorn/longhorn/issues/4601)

Remove resources block in values.yaml

---

chart/values.yaml

[Longhorn 4603](https://github.com/longhorn/longhorn/issues/4603)
(cherry picked from commit 61ad5112c120cc049cd9a6af70cc76ceca585e41)

[BACKPORT][v1.2.x]Remove resources block in values.yaml

---

chart/values.yaml

[Longhorn 4602](https://github.com/longhorn/longhorn/issues/4602)
(cherry picked from commit 61ad5112c120cc049cd9a6af70cc76ceca585e41)

[BACKPORT][v1.3.x]Remove resources block in values.yaml

---

chart/questions.yaml
chart/templates/storageclass.yaml
chart/values.yaml

This PR is link to the following issue [https://github.com/longhorn/longhorn/issues/4574]
add possibility to use nodeSelector on the storageClass #4574

Add nodeSelector to storageClass

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update system managed componente images for v1.3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.2-rc1

---

chart/questions.yaml

Fix: update outdated csi-image tags in chart/questions.yaml

---

examples/network-policy/recovery-backend-network-policy.yaml

example: add network policy for recovery backend

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.2-rc2

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

Add deleting-confirmation-flag setting

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.3.2

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update system managed component images for v1.2.6

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.6-rc1

---

examples/restore_to_file.yaml.template
scripts/restore-backup-to-file.sh

[Longhorn 1521](https://github.com/longhorn/longhorn/issues/1521)

improvement(restore): add script for restoring from backup file w/o having cluster

---

examples/restore_to_file.yaml.template
scripts/restore-backup-to-file.sh

[Longhorn 4756](https://github.com/longhorn/longhorn/issues/4756) 
(cherry picked from commit 7805007c99c7197b8d860db1850f24c373982d0f)
backport https://github.com/longhorn/longhorn/issues/1521

[BACKPORT][v1.3.3] improvement(restore): script for restoring from backup file

---

examples/restore_to_file.yaml.template
scripts/restore-backup-to-file.sh

[Longhorn 4757](https://github.com/longhorn/longhorn/issues/4757)
(cherry picked from commit 7805007c99c7197b8d860db1850f24c373982d0f)
backport https://github.com/longhorn/longhorn/issues/1521

[BACKPORT][v1.2.6] improvement(restore): script for restoring from backup file

---

enhancements/20220420-longhorn-snapshot-crd.md

Add LEP for Longhorn snapshot CRD feature

---

chart/questions.yml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

[v1.2.x]Update backing image manager tag to longhornio/backing-image-manager:v2_20221027

---

.github/workflows/community-issue.yml

ci: add community issue action
For https://github.com/longhorn/longhorn/issues/4701

ci: add community issue action

---

uninstall/uninstall.yaml

Keep the failed uninstallation job's pod to get logs for debugging

---

chart/Chart.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

Release 1.2.6

---

deploy/upgrade_responder_server/chart-values.yaml

Signed-off-by: Phan Le <phan.le@suse.com>

Add Longhorn v1.2.6 to upgrade response config

---

deploy/upgrade_responder_server/chart-values.yaml

Signed-off-by: Phan Le <phan.le@suse.com>

Add Longhorn v1.3.2 to upgrade response config

---

chart/questions.yml

Update version number 1.2.6 in question.yaml

---

chart/questions.yml

fix: correct the version of CSI-attacher and CSI-nodeDriverRegistrar for v1.2.x

---

enhancements/20220913-longhorn-system-backup-restore.md

https://github.com/longhorn/longhorn/issues/1455
[View file](https://github.com/longhorn/longhorn/blob/7e9de910c369b114060d2531c701b2b3b3b08cd3/enhancements/20220913-longhorn-system-backup-restore.md)

feat(system-backup/restore): add LEP

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)

chart: add engineReplicaTimeout

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

[Longhorn 4491](https://github.com/longhorn/longhorn/issues/4491)

Update longhorn-instance-manager to v2_20221115

---

enhancements/20221109-support-bundle-enhancement.md

https://github.com/longhorn/longhorn/issues/2759

feat(support-bundle): LEP

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4210
https://github.com/longhorn/longhorn/issues/3198

feat: Snapshot checksum calculation and verification

---

examples/crypto/secret-crypto-customized-rhel-FIPS-enabled.yaml
examples/crypto/secret-crypto-customized.yaml

Sync missing examples from longhorn-manager

---

chart/templates/storageclass.yaml
chart/values.yaml
deploy/longhorn.yaml
examples/storageclass.yaml

[Longhorn 4642](https://github.com/longhorn/longhorn/issues/4642)

feat: Added mkfsParams to storage class example

---

chart/questions.yaml
chart/templates/crds.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

longhorn/longhorn#4210
longhorn/longhorn#3198

chart: update longhorn-instance-manager to v2_20221123

---

chart/questions.yaml
chart/templates/clusterrole.yaml
chart/templates/clusterrolebinding.yaml
chart/templates/crds.yaml
chart/templates/daemonset-sa.yaml
chart/templates/default-setting.yaml
chart/templates/serviceaccount.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/2759

feat(support bundle): chart, YAML update

---

chart/templates/crds.yaml
deploy/longhorn.yaml

[Longhorn 3957](https://github.com/longhorn/longhorn/issues/3957)

local volume: update crds and manifests

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/2759

feat(support-bundle): image version bump

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml

1. update volume crd
2. update chart
longhorn/longhorn#2227

feat(backup): backup and restore recurring jobs

---

chart/questions.yaml
chart/templates/deployment-driver.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4875
https://github.com/longhorn/longhorn/issues/3907

[Backport][v1.3.3] feat(csi-liveness-probe): update chart and YAML

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml
examples/storageclass.yaml

Update YAMLs and Chart for Filesystem Trim

---

deploy/podsecuritypolicy.yaml

Add PSP yaml

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Included fix for multi-platform
https://github.com/longhorn/longhorn/issues/2759
https://github.com/rancher/support-bundle-kit/pull/59

chore: support-bundle-kit version bump

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

[Longhorn 4783](https://github.com/longhorn/longhorn/issues/4783)

chart: add fastReplicaRebuildEnabled setting

---

.github/ISSUE_TEMPLATE/refactor.md
.github/workflows/close-issue.yml
.github/workflows/create-issue.yml

Update backport github action due to lable change

---

chart/templates/crds.yaml
deploy/longhorn.yaml

chart: add conditions in engine/replica status.instanceStatus

---

scripts/environment_check.sh

environment_check.sh: check the hostname uniqueness

---

enhancements/20220727-dedicated-recovery-backend-for-rwx-volume-nfs-server.md

[Longhorn 2293](https://github.com/longhorn/longhorn/issues/2293)

Add LEP for Dedicated Recovery Backend for RWX Volume's NFS Server

---

enhancements/20221205-concurrent-backup-restore-limit.md

https://github.com/longhorn/longhorn/issues/4558

feat(lep): concurrent backup restore design

---

chart/templates/clusterrole.yaml
chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/1455

feat(system-backup/restore): chart, YAML update

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/4558

feat(concurrent-backup-restore): deploy update

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update system managed components' images to master-head

---

.codespellignore
.github/workflows/codespell.yml
enhancements/20210624-label-driven-recurring-job.md
enhancements/20210701-backing-image.md
enhancements/20220110-extend-csi-snapshot-to-support-longhorn-snapshot.md
enhancements/20220420-longhorn-snapshot-crd.md
enhancements/20221103-filesystem-trim.md

chore: add code spell

---

examples/crypto/storageclass-crypto-global.yaml
examples/crypto/storageclass-crypto-per-volume-dedicated-namespace.yaml
examples/crypto/storageclass-crypto-per-volume.yaml

example: Update comments of encrypto storageclasses for online expansion

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

build: 1.4.0-rc1

---

chart/templates/deployment-recovery-backend.yaml
chart/templates/deployment-webhook.yaml
chart/values.yaml

chart: support customized number of replicas of webhook and recovery-backend

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

bump support-bundle-kit version to v0.0.17
longhorn/longhorn#5107

build(image): bump support-bundle-kit

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

bump support-bundle-kit version to v0.0.17
longhorn/longhorn#5107

[BACKPORT][v1.4.x] build(image): bump support-bundle-kit

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

chart: add replicaFileSyncHttpClientTimeout

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

[BACKPORT][V1.4.0] chart: add replicaFileSyncHttpClientTimeout

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

build: 1.4.0-rc2

---

uninstall/uninstall.yaml

- https://github.com/longhorn/longhorn/issues/5132
- https://github.com/longhorn/longhorn/issues/5133

fix(uninstall): missing resource in ClusterRole

---

scripts/environment_check.sh

environment_check.sh: add nfs client kernel support

---

scripts/environment_check.sh

environment check: precisely check kernel option

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

build: 1.4.0-rc3

---

changelogs/changelog-1.4.0.md

release: add 1.4.0 changelog

---

CHANGELOG/CHANGELOG-1.4.0.md

release: update 1.4.0 changelog

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

build: 1.4.0

---

chart/questions.yaml

Fix incorrect formatting in `question.yaml` and validate by importing in Rancher.

fix: Correct formatting error in `question.yaml` file

---

deploy/upgrade_responder_server/chart-values.yaml

Add Longhorn v1.4.0 in upgrade responder server

---

chart/questions.yaml

fix: fix the `CSI Liveness Prob` group in questions.yaml

---

chart/README.md

Update uninstallation info to include the 'Deleting Confirmation Flag ' in chart

---

deploy/prerequisite/longhorn-iscsi-installation.yaml

update iscsi installation image to latest alpine.

---

chart/templates/crds.yaml
deploy/longhorn.yaml

backup: update crds

---

scripts/environment_check.sh

After #5310 the old #5305 was closed due to merge conflicts.
These are solved now, and it can be merged again automatically

Fix for bug #5304 (second version including POSIX way to call subroutine)

---

chart/README.md
chart/questions.yaml
chart/templates/validate-psp-install.yaml
deploy/longhorn.yaml

Update PSP validation

---

enhancements/20230116-smb-cifs-backup-store-support.md

Add LEP for SMB/CIFS Backup Store Support

---

deploy/prerequisite/longhorn-cifs-installation.yaml

Add cifs-utils installation manifest

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn-manager/pull/1697

fix(crd): description

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/3836

feat(recurring-job): update CRD for new tasks

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/4893
https://github.com/longhorn/longhorn/issues/3836

[BACKPORT][v1.3.3] feat(recurring-job): periodically cleanup snapshots

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5109
https://github.com/longhorn/longhorn/issues/3836

[BACKPORT][v1.4.1] feat(recurring-job): periodically cleanup snapshots

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

ref: https://github.com/longhorn/longhorn/issues/5445

release: 1.4.1-rc1

---

chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5467

fix(support-bundle): version bump

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: 1.4.1-rc2

---

examples/data_migration.yaml

Fix data migration example to include hidden files

---

enhancements/20220420-longhorn-snapshot-crd.md

docs: fix typo

---

chart/README.md

ref: [longhorn/longhorn#5399](https://github.com/longhorn/longhorn/issues/5399)

doc: update prerequisites in chart readme to make it consistent with documentation master

---

chart/README.md

ref: [longhorn/longhorn#5399](https://github.com/longhorn/longhorn/issues/5399)

doc: update prerequisites in chart readme to make it consistent with documentation v1.3.x

---

chart/README.md

ref: [longhorn/longhorn#5399](https://github.com/longhorn/longhorn/issues/5399)

doc: update prerequisites in chart readme to make it consistent with documentation v1.4.x

---

enhancements/20230307-pdb-for-longhon-csi-and-webhook.md

Add LEP: Use PDB to protect Longhorn components from drains

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Update YAML and chart files for v1.3.x
Update `longhorn-instance-manager` version from `v1_20221003` to ~v1_20230223~ `v1_20230310`
longhorn/longhorn#5265

chore(version-bump): longhorn-instance-manager

---

enhancements/20230309-recurring-filesystem-trim.md

https://github.com/longhorn/longhorn/issues/5186

feat(lep): recurring filesystem trim design

---

enhancements/20230307-pdb-for-longhon-csi-and-webhook.md

Update the LEP: Use PDB to protect Longhorn components from drains

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

Add nodeDrainPolicy setting

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

[Longhorn 5073](https://github.com/longhorn/longhorn/issues/5073)
- New parameter: `SUPPORT_BUNDLE_COLLECTOR` to execute specified support-bundle-kit collector

feat(support-bundle): version bump to v0.0.20

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Update chart and YAML files for new tasks.
longhorn/longhorn#4898

feat(recurring-job): update CRDs

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Ref: longhorn/longhorn 5443
update backing image manager image tag

chore(version-bump): backing-image-manager

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5614

chore(support-bundle): version bump

---

deploy/longhorn-images.txt

https://github.com/longhorn/longhorn/pull/5718

fix(v1.4.x): mergify conflicts

---

deploy/upgrade_responder_server/chart-values.yaml

Release v1.4.1 in the upgrade responder server

---

enhancements/20230418-azure-blob-storage-backup-store-support.md

LEP for Azure Blob Storage  Backup Store Support

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5186

feat(recurring-job): filesystem trim

---

enhancements/20230303-consolidate-instance-managers.md

https://github.com/longhorn/longhorn/issues/5208

feat(lep): consolidate instance managers

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5208

feat: consolidate instance managers

---

deploy/prerequisite/longhorn-nvme-cli-installation.yaml

https://github.com/longhorn/longhorn/issues/5738

prerequisite: add nvme-cli installation manifest

---

chart/templates/preupgrade-job.yaml

Add helm hook `pre-upgrade` file `preupgrade-job.yaml` to protect the system from unsupported upgrade path.
longhorn/longhorn#5131

feat: introduce helm hook `pre-upgrade`

---

scripts/environment_check.sh

Longhorn/longhorn#5738
Longhorn/longhorn#5380

Environment check for SPDK support

---

enhancements/20230420-upgrade-checker-info-collection.md

https://github.com/longhorn/longhorn/issues/5235

feat(lep): upgrade checker info collection

---

deploy/upgrade_responder_server/chart-values.yaml

longhorn/longhorn#5581
longhorn/longhorn#5884

Release v1.3.3 in Longhorn upgrade responder

---

scripts/environment_check.sh

Update environment_check.sh for SPDK feature

---

scripts/environment_check.sh

prerequisite: check SSE4.2 on x86-64 platform for SPDK feature

---

dev/upgrade-responder/README.md
dev/upgrade-responder/install.sh
dev/upgrade-responder/manifests/grafana.yaml
dev/upgrade-responder/manifests/influxdb.yaml

https://github.com/longhorn/longhorn/issues/5235

feat(upgrade-responder): setup dev environment

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/5358

feat: add softAntiAffinity and zoneSoftAntiAffiny to volume spec

---

deploy/upgrade_responder_server/chart-values.yaml

Release v1.4.2 into Longhorn upgrade responder

---

chart/templates/clusterrole.yaml
chart/templates/crds.yaml
deploy/longhorn.yaml

Update chart for new AD refactoring

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

ref: [longhorn/longhorn#5888](https://github.com/longhorn/longhorn/issues/5888)

feat(log): add global setting for log level

---

enhancements/20230517-set-recurring-job-to-pvc.md

https://github.com/longhorn/longhorn/issues/5791

feat(lep): set RecurringJob to PVCs design

---

chart/questions.yaml
chart/templates/network-policies/backing-image-data-source-network-policy.yaml
chart/templates/network-policies/backing-image-manager-network-policy.yaml
chart/templates/network-policies/instance-manager-networking.yaml
chart/templates/network-policies/manager-network-policy.yaml
chart/templates/network-policies/recovery-backend-network-policy.yaml
chart/templates/network-policies/ui-frontend-network-policy.yaml
chart/templates/network-policies/webhook-network-policy.yaml
chart/values.yaml

ref: [longhorn/longhor#5403](https://github.com/longhorn/longhorn/issues/5403)

feat(network policy): add network policy into chart

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5917

chore: remove Engine/ReplicaManagerCPURequest in Node CRD

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: [longhorn/longhorn#3506](https://github.com/longhorn/longhorn/issues/3506)
blocked by:
- https://github.com/longhorn/longhorn-manager/pull/1904

feat(backup): store storage class name to backup volume

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/2865

chore: remove deprecated recurring jobs field

---

enhancements/20230420-engine-identity-validation.md

#5845
See the following draft PRs for a POC implementation of this general approach.
- https://github.com/longhorn/longhorn-engine/pull/902
- https://github.com/longhorn/longhorn-instance-manager/pull/229
- https://github.com/longhorn/longhorn-manager/pull/1897

Engine Identity Validation LEP

---

chart/questions.yaml

ref: [longhorn/longhorn#5888](https://github.com/longhorn/longhorn/issues/5888)

fix: change log level to Debug

---

enhancements/20230526-volume-backup-policy-for-longhorn-system-backup.md

https://github.com/longhorn/longhorn/issues/5011

feat(lep): volume backup policy for Longhorn system backup design

---

deploy/backupstores/azurite-backupstore.yaml
deploy/backupstores/minio-backupstore.yaml
deploy/backupstores/nfs-backupstore.yaml

Add the Azurite manifest to start Azurite server for local testing
Ref: longhorn/longhorn#1309, https://github.com/longhorn/longhorn-tests/pull/1382

feat(backupstore): add azurite emulator

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/5011

feat(system-backup): update SystemBackup CRD for volume backup policy

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/3289

chore: remove deprecated fields

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

Remove deprecated allow-node-drain-with-last-healthy-replica setting

---

chart/values.yaml

Removing a space between the key and colon.

fix: (chart) fix nodeDrainPolicy key

---

scripts/environment_check.sh

spdk: update expected-nr-hugepages to 512 in environment_check.sh

---

scripts/environment_check.sh

spdk: nvme-cli should be between 1.12 and 1.16

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml

Support offline rebuilding for SPDK volumes

---

chart/questions.yaml

Reduce BackupConcurrentLimit and RestoreConcurrentLimit to 2

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

from v1_20230407 to v1_20230616
Ref: longhorn/longhorn#4927

update: update instance-manager image version

---

enhancements/20230616-automatic-offline-replica-rebuild.md

LEP for automatic-offline-replica-rebuild

---

deploy/backupstores/nfs-backupstore.yaml

Remove an extra error line in backupstore/nfs-backupstore.yaml.

fix(deploy): remove error line in nfs backupstore

---

dev/upgrade-responder/install.sh

https://github.com/longhorn/upgrade-responder/issues/47
https://github.com/longhorn/longhorn/issues/5235

feat(upgrade-responder): support requestSchema in setup script

---

uninstall/uninstall.yaml

Add volumeattachments resource to Longhorn ClusterRole

---

chart/questions.yaml

https://github.com/longhorn/longhorn/issues/6257

fix(chart): update default setting log level

---

chart/questions.yaml

Fix some small errors on StorageClass NodeSelector.

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

- Add the setting added in https://github.com/longhorn/longhorn-manager/pull/1731 in the helm chart
- Related to https://github.com/longhorn/longhorn/issues/5208

chart: Update settings based on the instance managers consolidation

---

enhancements/20230718-disk-anti-affinity.md

Add LEP for disk anti-affinity

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

ref: [longhorn/longhorn#4826](https://github.com/longhorn/longhorn/issues/4826)

feat(setting): add allow empty disk node selector volume setting

---

enhancements/20230807-backingimage-backup-support.md

ref: [longhorn/longhorn#4165](https://github.com/longhorn/longhorn/issues/4165)

lep(backingimage): backingimage backup support

---

enhancements/20230815-engine-upgrade-enforcement.md

https://github.com/longhorn/longhorn/issues/5842

feat(lep): engine upgrade enforcement design

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

~https://github.com/longhorn/longhorn/issues/6338~
https://github.com/longhorn/longhorn/issues/6544

feat(support-bundle): version bump

---

enhancements/20230420-engine-identity-validation.md

#5845 
FYI @PhanLe1010. Made some changes to the LEP based on my final implementation in https://github.com/longhorn/longhorn-engine/pull/902.

Modify Engine Identity Validation LEP for changes to longhorn-engine PR

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml
deploy/upgrade_responder_server/README.md
deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Add ReplicaDiskSoftAntiAffinity setting

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Replace spec.engineImage with spec.Image in volume, replica and engine resources

---

deploy/longhorn-images.txt

https://github.com/longhorn/longhorn/issues/6737

task: use head images for security scan

---

examples/storageclass.yaml
examples/v2/storageclass.yaml

Add nfsOptions parameter to sample storageclass.yaml

---

enhancements/20220428-storage-network-through-grpc-proxy.md
enhancements/20230526-volume-backup-policy-for-longhorn-system-backup.md
enhancements/20230807-backingimage-backup-support.md

Fixed some typos that codespell found.

fix(typo): codespell tested failed

---

scripts/environment_check.sh

Add kernel release check to environment_check.sh

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.4.4-rc1

---

scripts/environment_check.sh

This is backport of https://github.com/longhorn/longhorn/pull/6906

[Backport v1.4.4] Fix bug: check script fails to perform all checks

---

scripts/environment_check.sh

This is backport of https://github.com/longhorn/longhorn/pull/6906

[Backport v1.3.x]Fix bug: check script fails to perform all checks

---

enhancements/20220428-storage-network-through-grpc-proxy.md
uninstall/uninstall.yaml

fix: incorrect manager image in uninstall manifest

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.4.4-rc2

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.2-rc1

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.2-rc2

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.2-rc3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.2

---

deploy/upgrade_responder_server/chart-values.yaml

longhorn/longhorn#6894
longhorn/longhorn#6981

Fix bug in config file and release v1.4.4, v1.5.2

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.3-rc1

---

enhancements/20230905-automatically-evict-replicas-while-draining.md

Automatically evict replicas while draining LEP

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/6916
https://github.com/longhorn/longhorn/issues/6922
https://github.com/longhorn/security/issues/16

fix: CVE issues

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.3

---

chart/templates/daemonset-sa.yaml
chart/templates/deployment-driver.yaml
chart/values.yaml

https://github.com/longhorn/longhorn/issues/5681

feat: add GOCOVERDIR for deployment

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/7152

fix(cve): support-bundle

---

chart/questions.yaml
chart/templates/crds.yaml
deploy/longhorn.yaml

#2238
The LEP at https://github.com/longhorn/longhorn/pull/6643 is largely finalized and this PR is ready for review based on the latest language there.

Automatically evict replicas while draining deployment changes

---

.github/workflows/create-issue.yml

ci: fix creating backport issue failed if assignee isn't a longhorn member
For https://github.com/longhorn/longhorn/issues/7201

ci: fix creating backport issue failed if assignee isn't a longhorn member

---

chart/Chart.yaml

https://github.com/longhorn/longhorn/issues/7224

build: bump up the minimum supported Kubernetes version

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

ref: https://github.com/longhorn/longhorn/issues/6978
Add setting `DetachManuallyAttachedVolumesWhenCordoned default to `false`
Note: the changes in the `chart/README.md` is auto generated. see [here](https://github.com/longhorn/longhorn/wiki/document-convention)

feat(node drain): add DetachManuallyAttachedVolumesDuringDrain setting

---

chart/Chart.yaml

This reverts commit 6ad473c1b68da13da8337489eefcc5cab26dd891.
https://github.com/longhorn/longhorn/issues/7224

revert: "build: bump up the minimum supported Kubernetes version"

---

enhancements/20231204-default-priority-class.md

Add a default priority class with the highest value to the setting `priority-class`.
Ref: longhorn/longhorn#6528

feat(lep): default priority class

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/7277

fix(cve): support-bundle-kit

---

.github/workflows/create-issue.yml

ci(gh-action): add github action for automatically creating ui ticket
For https://github.com/longhorn/longhorn/issues/7278

ci(gh-action): add github action for automatically creating ui ticket

---

deploy/upgrade_responder_server/chart-values.yaml

longhorn/longhorn#7082
longhorn/longhorn#7105

Release v1.5.3 and bump memmory request/limit for upgrade responder

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

https://github.com/longhorn/longhorn/issues/6033

feat(metrics): add schema for SPDK info collection to upgrade responder

---

enhancements/20230814-talos-linux-support.md

https://github.com/longhorn/longhorn/issues/3161

feat(lep): Talos Linux support design

---

enhancements/20230821-customize-maximum-recurring-job-retain-number.md

feat(lep): customize maximum recurring job retain

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/templates/preupgrade-job.yaml
chart/templates/priorityclass.yaml
chart/values.yaml
deploy/longhorn.yaml

Add a priority class template YAML file to create a default priority class.
Add a new field `defaultPriorityClassName` in value.yaml.
Update the deploy YAML file - longhorn.yaml
Ref: longhorn/longhorn#6528

feat: default priority class

---

chart/README.md
chart/questions.yaml
chart/values.yaml

Revise default over-provisioning percentage to 100.

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

Add the `recurringJobMaxRetention` default setting and update the README.md file.
ref: longhorn/longhorn#5713

feat(recurringjob): add RecurringJobMaxRetention setting

---

chart/README.md
chart/README.md.gotmpl

fix: remove helm 2 support

---

chart/templates/crds.yaml
deploy/longhorn.yaml

chart: seperate v1 and v2 instanceManagers

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/7384

chore(image): csi component version update

---

enhancements/20230815-engine-upgrade-enforcement.md

https://github.com/longhorn/longhorn/issues/5842

doc(enhancement): Rewrite motivation

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/6386

feat(crd): add error msg to engine replica status

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

chart: introduce v1-data-engine setting

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Ref: longhorn/longhorn#7423, https://github.com/longhorn/longhorn-manager/pull/2414

fix(volume): add a field "FSType" in Node.Status.DiskStatus

---

chart/templates/crds.yaml
deploy/longhorn.yaml
enhancements/20230523-support-spdk-volumes.md
examples/v2/storageclass.yaml

chart: rename backendStoreDriver to dataEngine

---

chart/templates/clusterrole.yaml
chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/4165

feat(backingimage): backup backing image support

---

enhancements/20230807-backingimage-backup-support.md

ref: https://github.com/longhorn/longhorn/issues/4165

doc(backupbackingimage): add example yaml of backingimage backup and restore

---

chart/templates/crds.yaml
deploy/longhorn.yaml
enhancements/20230905-snapshot-space-management.md

Ref: https://github.com/longhorn/longhorn/issues/6563

feat: add snapshot space management lep

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/prerequisite/longhorn-spdk-setup.yaml
scripts/environment_check.sh

Issue https://github.com/longhorn/longhorn/issues/7606

Incease default hugepage size for v2 data engine to 2GiB

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Issue longhonr/longhorn#7539
Introuce a new field `Incompatible` in `EngineImage.Status` and remove the state `EngineImageStateIncompatible`.

fix(upgrade): skip to check engine upgrade path

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#7173
cc @mantissahz

fix: sync crd from longhorn-manager repo

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.0-rc1

---

uninstall/uninstall.yaml

ref: https://github.com/longhorn/longhorn/issues/7643
Add backupbackingimage to the uninstall clusterrole

fix: add backupbackingimage to clusterrole

---

uninstall/uninstall.yaml

ref: https://github.com/longhorn/longhorn/issues/7643
Fix typos, should be plural

fix: fix typos in uninstall yaml

---

chart/questions.yaml

Add missing warnings in the questions.yaml

---

chart/README.md
chart/README.md.gotmpl
chart/questions.yaml
chart/values.yaml

ref: longhorn/longhorn 7667
Basically the copy/paste from the PR https://github.com/longhorn/website/pull/835

fix(doc): update the description in helm values

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.0-rc2

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/6386
Add conditions to instance-manager crd

feat(mount): process manager periodically check mount status and update engine condition

---

chart/templates/default-setting.yaml

Issue https://github.com/longhorn/longhorn/issues/7460
Correct the format of the chart/templates/default-setting.yaml.

charts: fix the default-setting cm format issue

---

chart/questions.yaml

longhorn/longhorn#7776
More details at https://github.com/longhorn/longhorn/issues/7496#issuecomment-1909146497

Fix duplicated quotation causing Rancher terraform fails to deploy longhorn chart

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Issue Ref: longhorn/longhorn#7423, longhorn/longhorn#7429
Backport `[IMPROVEMENT] Improve handling of 16TiB+ volumes with ext4 as the underlying file system`

fix(volume): add a new field "FSType" in Node.Status.DiskStatus

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.0-rc3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.0

---

chart/templates/servicemonitor.yaml
chart/values.yaml

Issue # https://github.com/longhorn/longhorn/issues/7864, https://github.com/longhorn/longhorn/issues/7041
Backport to v1.5.x

Add ServiceMonitor in helm chart (#6157)

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.4-rc2

---

README.md

Fixed CNCF logo error in README
Issue #

Fixed CNCF logo error in README

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

chart: Add Snapshot Maximum Count to the Settings

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.4-rc3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.4-rc4

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.4

---

CHANGELOG/CHANGELOG-1.5.4.md

Issue #7878 
This PR is cloned from the 1.6.0 note with minor changes.

release: add 1.5.4 release note

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Issue longhorn/longhorn#8159
- Update support-bundle image version to v0.0.36
`None`
`None`

chore(support-bundle): update image version

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.1-rc1

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.1-rc2

---

scripts/environment_check.sh

environment_check.sh: add checks for dmcrypt and dmsetup utilities

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

settings: add v2DataEngineLogFlags and v2DataEngineLogLevel

---

chart/templates/crds.yaml
deploy/longhorn.yaml

crd: introduce disk driver in node.spec.diskSpec

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.1-rc3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.1

---

CHANGELOG/CHANGELOG-1.6.1.md

release: add 1.6.1 release note

---

chart/templates/crds.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/7923
Pull in the CRD changes from https://github.com/longhorn/longhorn-manager/pull/2680

crd: Add virtual size to backing images

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.5-rc1

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt

Mirror the quay.io/openshift/origin-oauth-proxy image to Longhorn repo and update the chart

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.5-rc2

---

chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Issue longhorn/longhorn#8372
Fix CVE vulnerabilities.
This needs to backport to master and 1.6.

fix(cve): update support-bundle-kit to v0.0.37

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.5.5

---

CHANGELOG/CHANGELOG-1.5.5.md

release: add 1.5.5 release note

---

chart/README.md
chart/values.yaml

Issue # longhorn/longhorn#7889

doc(chart): update README.md of chart

---

deploy/upgrade_responder_server/chart-values.yaml

Release v1.5.5 to upgrade responder server

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.2-rc1

---

.github/mergify.yml

chore: auto approve and merge mergify PR

---

.github/mergify.yml

Issue https://github.com/longhorn/longhorn/issues/8554

chore: fix mergify unable to approve its PR

---

chart/templates/crds.yaml
deploy/longhorn.yaml

crd: add instanceManagerName in node.status.diskStatus

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.2-rc2

---

enhancements/20220913-longhorn-system-backup-restore.md

ref: https://github.com/longhorn/longhorn/issues/5085
We now support backup backingimages when doing system backup
Update the lep.

doc(lep): update system backup lep for backup bacingimages

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.2

---

CHANGELOG/CHANGELOG-1.6.2.md

release: add 1.6.2 release note

---

README.md

release: set 1.6.2 as the latest version

---

chart/README.md
chart/templates/daemonset-sa.yaml
chart/templates/deployment-driver.yaml
chart/templates/deployment-ui.yaml
chart/templates/postupgrade-job.yaml
chart/templates/preupgrade-job.yaml
chart/templates/uninstall-job.yaml
chart/values.yaml

ref: https://github.com/longhorn/longhorn/issues/5089
- Add global tolerations and nodeselectors for user deployed components
- Use global setting by default
- Override each by their specific settings .

feat(chart): introduce global tolerations and nodeselectors for user deployed components

---

CHANGELOG/CHANGELOG-1.6.0.md
enhancements/20230417-extend-csi-snapshot-to-support-backingimage.md

Issue `None`
Fix codespell failures.
`None`
`None`

fix: codespell failures.

---

enhancements/20240522-storage-network-for-rwx-volumes.md

This LEP proposes to extend Longhorn's storage network feature to support RWX volumes.
None.
None.

feat(LEP): storage network for RWX volumes

---

README.md

Mark 1.6.2 as a stable release

---

deploy/upgrade_responder_server/chart-values.yaml

longhorn/longhorn#8579
```bash
➜  upgrade-responder git:(v0.2.0) ✗ curl -d {} https://longhorn-upgrade-responder.rancher.io/v1/checkupgrade | json_pp
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   519  100   517  100     2   1339      5 --:--:-- --:--:-- --:--:--  1344
{
"requestIntervalInMinutes" : 60,
"versions" : [
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.3.3",
"releaseDate" : "2023-04-19T00:00:00Z",
"tags" : [
"stable"
]
},
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.4.4",
"releaseDate" : "2023-10-26T00:00:00Z",
"tags" : [
"stable"
]
},
{
"extraInfo" : null,
"minUpgradableVersion" : "",
"name" : "v1.5.5",
"releaseDate" : "2024-04-19T00:00:00Z",
"tags" : [ …
```

Release Longhorn v1.6.2 and mark it stable

---

enhancements/20240314-recurring-and-manual-full-backup-support.md

- Add `ExecutionCount` to the recurringJob Status
- `BackupMode` to the `Backup` Spec

Lh7070 support full backup

---

enhancements/20240522-storage-network-for-rwx-volumes.md

The current LEP doesn't fully address how pre-existing RWX volume workloads will behave during and after the upgrade to Longhorn v1.7.0 when the cluster has the storage network configured before the upgrade. This PR proposes to complete the upgrade scenarios.
- Behavior: https://github.com/longhorn/longhorn-tests/pull/1921

feat(lep): storage network for RWX volumes: upgrade scenario

---

chart/README.md
chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn.yaml
deploy/upgrade_responder_server/chart-values.yaml

longhorn/longhorn#2187
Adds the global and volume specific FreezeFSForSnapshot setting and field.

Add a global FreezeFS setting and a volume FreezeFS field

---

enhancements/20240522-storage-network-for-rwx-volumes.md

After discussing with @innobead , we think it would make sense to introduce a new setting to control the application of the storage network to RWX volumes. This change will eliminate the workload pod restart combination after the upgrade due to pre-existing RWX volumes. And, it will give users better control over whether they are willing to tolerate the RWX volume workload pod restart after the CSI plugin pod restart.
`None`
`None`

feat(LEP): storage network for RWX volumes: control by setting

---

enhancements/20240612-backing-image-encryption-and-clone-supprt.md

ref: https://github.com/longhorn/longhorn/issues/7051
- Add LEP for backing image encryption support

feat(lep): backing image clone and encryption support

---

enhancements/20240516-pre-pull-images.md

Issue # longhorn/longhorn#8376

feat(lep): pre-pull share-manager/instance-manager images

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/7051
Check the LEP here: https://github.com/longhorn/longhorn/pull/8740

feat(backingimage): add clone source type and secret to the backing image

---

scalability/reference-setup-performance-scalability-and-sizing-guidelines/README.md

Update README.md for the scalability report

---

chart/templates/crds.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/7070
- Add `.Status.BackupCount` to BackupVolume. 
- Add `.Status.NewlyUploadedDataSize` and `.Status.ReUploadedDataSize` to  Backup

feat(CRD): update CRD for full backup

---

chart/templates/services.yaml
deploy/longhorn.yaml

See explanation at https://github.com/longhorn/longhorn/issues/8844#issuecomment-2197769331
longhorn/longhorn#8844

Remove headless services for instance manager pods

---

.github/workflows/generate-sbom.yml

Issue https://github.com/longhorn/longhorn/issues/8821
generate sbom for component images and upload to release assets

ci: generate sbom for component images and upload to release assets

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Update CRD for cloning retry logic

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Issue longhorn/security#20
Fix support-bundle-kit CVE vulnerabilities.
`None`
`None`

fix(cve): update support-bundle-kit to v0.0.39

---

chart/templates/crds.yaml
deploy/longhorn.yaml

chore(chart): update crds.yaml

---

chart/templates/crds.yaml
deploy/longhorn.yaml

This reverts commit 0b75cdbdd79caf2209cc7c138b856e1626eca92d.
https://github.com/longhorn/longhorn-manager/pull/2815#discussion_r1661497330
`None`
https://github.com/longhorn/longhorn/pull/8631

Revert "feat(storage-network): add workloadsStatus.podNamespace to Volume CRD"

---

deploy/longhorn-okd.yaml
scripts/generate-longhorn-yaml.sh

Issue # longhorn/longhorn#8300
Longhorn can be installed by the deploy manifest file on the OpenShift platform.

fix(deploy): add a deploying manifest file with OpenShift enabled.

---

chart/templates/crds.yaml
deploy/longhorn.yaml

feat(v2 upgrade/chart): update for the changes in the data plane

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#8976
Before:
```
longhornio/support-bundle-kit:v0.0.39 (suse linux enterprise server 15.5)
Total: 1 (HIGH: 1, CRITICAL: 0)
┌─────────┬─────────────────────┬──────────┬────────┬─────────────────────┬─────────────────────┬──────────────────────────┐
│ Library │    Vulnerability    │ Severity │ Status │  Installed Version  │    Fixed Version    │          Title           │
├─────────┼─────────────────────┼──────────┼────────┼─────────────────────┼─────────────────────┼──────────────────────────┤
│ krb5    │ SUSE-SU-2024:2302-1 │ HIGH     │ fixed  │ 1.20.1-150500.3.6.1 │ 1.20.1-150500.3.9.1 │ Security update for krb5 │
└─────────┴─────────────────────┴──────────┴────────┴────────── …
```

Fix(cve): update support-bundle-kit to v0.0.40

---

chart/Chart.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

chore(version): update chart version and appVersion to v1.8.0-dev

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.7.0-rc2

---

chart/README.md
chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

chart: remove offlineReplicaRebuilding

---

deploy/prerequisite/longhorn-cifs-installation.yaml
deploy/prerequisite/longhorn-gke-cos-node-agent.yaml
deploy/prerequisite/longhorn-iscsi-installation.yaml
deploy/prerequisite/longhorn-iscsi-selinux-workaround.yaml
deploy/prerequisite/longhorn-nfs-installation.yaml
deploy/prerequisite/longhorn-nvme-cli-installation.yaml
deploy/prerequisite/longhorn-spdk-setup.yaml

Issue https://github.com/longhorn/longhorn/issues/8855
Add longhorn-system namespace to installer daemonsets

Add longhorn-system namespace to installer daemonsets

---

.github/workflows/migrate_zenhub_board_to_github_project.py
.github/workflows/migrate_zenhub_board_to_github_project.yml

ci(workflow): add "Migrate ZenHub Board to GitHub Project" GitHub Action

---

.github/workflows/migrate_zenhub_board_to_github_project.yml

fix(workflow): fix python file path of "Migrate ZenHub Board to GitHub Project"

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.7.0-rc3

---

.github/workflows/migrate_zenhub_board_to_github_project.yml

fix(workflow): fix arguments of python file path of "Migrate ZenHub Board to GitHub Project"

---

.github/workflows/conventional_commits.yml

Issue #
Fix complaint from workload execution, hopefully.
Make `longhorn/.github/workflows/conventional_commits.yml` match `longhorn-manager`'s.

fix(workflow): add missing tag for pull request action.

---

.github/workflows/migrate_zenhub_board_to_github_project.py

Issue longhorn/longhorn#9155
ZenHub doesn't have closed pipeline, so we need to iterate through all closed issues in the GitHub repo.

fix(workflow): fix closed tickets to project board

---

deploy/longhorn-images.txt

chore: add longhorn-cli in longhorn-images.txt

---

deploy/longhorn-images.txt

[V1.7.x] chore: add longhorn-cli in longhorn-images.txt

---

.github/ISSUE_TEMPLATE/bug.md

chore(github): add Workaround and Mitigation in bug template

---

.github/ISSUE_TEMPLATE/release.md

chore(template): update Release task

---

CHANGELOG/CHANGELOG-1.7.0.md

docs(release): add 1.7.0 release note

---

CHANGELOG/CHANGELOG-1.7.0.md

docs(release): update 1.7.0 release note

---

README.md

docs(release): update README.md

---

CHANGELOG/CHANGELOG-1.7.0.md

docs(1.7.0): add PSA for issue 9267

---

deploy/backupstores/azurite-backupstore.yaml

Issue # longhorn/longhorn#8965
The API of 3.23.0 is outdated for the azblob 1.4.0 of azure SDK.

chore(deploy): bump the azurite version to 3.30.0

---

.github/workflows/scan_and_notify_testing_items.py
.github/workflows/scan_and_notify_testing_items.yml

feat(ci): automatically scan and notify testing items every Sunday

---

.github/workflows/scan_and_notify_testing_items.py
.github/workflows/scan_and_notify_testing_items.yml

fix(ci): ifx automatically scan and notify testing items

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#9354
Before:
```
longhornio/support-bundle-kit:v0.0.41 (suse linux enterprise server 15.6)
Total: 2 (HIGH: 2, CRITICAL: 0)
┌──────────┬─────────────────────┬──────────┬────────┬───────────────────┬────────────────────┬──────────────────────────┐
│ Library  │    Vulnerability    │ Severity │ Status │ Installed Version │   Fixed Version    │          Title           │
├──────────┼─────────────────────┼──────────┼────────┼───────────────────┼────────────────────┼──────────────────────────┤
│ curl     │ SUSE-SU-2024:2784-1 │ HIGH     │ fixed  │ 8.6.0-150600.2.2  │ 8.6.0-150600.4.3.1 │ Security update for curl │
├──────────┤                     │          │        │ …
```

fix(cve): update support-bundle-kit to v0.0.42

---

chart/templates/daemonset-sa.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue # longhorn/longhorn#9153
Get modules information from /boot/config-$(uname -r) on the host.

fix(node): mount host's directory `/boot/`

---

chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

feat(v2 volume/configurable cpu mask): updata crds.yaml and longhorn.yaml

---

CHANGELOG/CHANGELOG-1.7.1.md

docs(release): update 1.7.1 release note

---

chart/templates/crds.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#8835
Fix chart and YAML.
`None`
`None`

fix(deploy): dataEngineSpec

---

deploy/longhorn-okd.yaml

Issue longhorn/longhorn#8835
Fix OKD YAML.
`None`
`None`

fix(deploy/okd): dataEngineSpec

---

chart/README.md
chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml

Issue # longhorn/longhorn#8954 longhorn/longhorn#8319

fix(setting): add a default setting `backupExecutionTimeout`

---

.github/workflows/add-to-projects.yml

Issue Longhorn/longhorn#9411
A newly created community issue's sprint is `current`.

chore(ci): update status and sprint of community issues

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.3-rc1

---

.github/workflows/add-to-projects.yml

Update the issue status in the community project only if it already exists
https://github.com/longhorn/longhorn/actions/runs/10789495323/job/29922610839

chore(action): update issue status in community project

---

chart/templates/crds.yaml
deploy/longhorn.yaml

fix(chart): update crd.yaml

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.3-rc2

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.3

---

.github/workflows/generate-sbom.yml

chore(workflow): add generate-sbom.yml

---

.github/ISSUE_TEMPLATE/release.md

chore(template): update release.md

---

.github/workflows/generate-sbom.yml

chore(workflow): update generate-sbom.yml

---

.github/workflows/check-sprint-last-day.py
.github/workflows/update-community-issue-sprint.yml

chore(workflow): automatically move new community issues to next sprint

---

.github/workflows/add-to-projects.yml
.github/workflows/update-projects.yaml

fix(workflow): ignore issue event from an invalid user such as mergify[bot]

---

.github/workflows/update-issue-sprint.yml

chore(workflow): clean up the sprint field at the end of each sprint

---

chart/README.md
chart/questions.yaml
chart/templates/deployment-ui.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml

Signed-off-by: Derek Su <derek.su@suse.com>#### Which issue(s) this PR fixes:
Issue Longhorn/longhorn#9597

feat(chart): remove mirrored openshift image from Longhorn

---

enhancements/20241003-improve-pulling-backups-from-the-backup-target.md

Issue # longhorn/longhorn#9530

docs(lep): improve pulling backups trom the remote backup target

---

chart/README.md
scripts/update-chart-readme.sh

chore(scripts): add a script for updating chart/README.md

---

chart/templates/storageclass.yaml
chart/values.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

https://github.com/longhorn/longhorn/issues/9584

chore: set data engine explicitly for the default storageclass

---

.github/workflows/migrate-zenhub-board-to-github-project.py
.github/workflows/migrate-zenhub-board-to-github-project.yml
.github/workflows/scan-and-notify-testing-items.py
.github/workflows/scan-and-notify-testing-items.yml

fix(workflow): fix script paths

---

CHANGELOG/CHANGELOG-1.7.1.md
CHANGELOG/CHANGELOG-1.7.2.md

docs(release): update 1.7.2 release note

---

README.md

docs(release): update v1.7.2 to the latest version of v1.7.x

---

.github/ISSUE_TEMPLATE/regular-tasks-for-release.md

chore(template): add  Regular Tasks for Feature Release template

---

README.md

chore(release): mark v1.7.2 as stable release

---

MAINTAINERS

Issue #
Thank you, @ejweber, for your contributions in the past!

chore: remove inactive member from maintainer list

---

deploy/upgrade_responder_server/chart-values.yaml

chore: release v1.7.2 into upgrade responder

---

enhancements/20241111-rwx-resize.md

Issue https://github.com/longhorn/longhorn/issues/9736
LEP for forwarding RWX resize requests to be handled on the node with the share manager on it.

docs(lep): rwx resize improvement

---

.github/workflows/scan-and-notify-testing-items.py

fix(workflow): update wording

---

.github/workflows/update-issue-sprint.yml

fix: fix update-issue-sprint.yml permissions and support QA Sprint update

---

README.md

docs: mark v1.5.x as EOL

---

scripts/environment_check.sh

Issue longhorn/longhorn#9830
The env check script is deprecated. This change should be applied only on 1.6.x, not included on master and 1.7.x.

revert(#9952): env script check nfs version in nfsmount

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Update CRDs
longhorn/longhorn#6361

feat: v2 live migration

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

for multiple backup stores
Issue # longhorn/longhorn#5411

fix(backup): add and update columns into backup related CRD 

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

ref: https://github.com/longhorn/longhorn/issues/6341

feat: update crd for v2 backing image

---

chart/Chart.yaml
chart/README.md
chart/README.md.gotmpl

feat(chart): update minimum kubernetes supported to 1.25

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#9684
Update CSI components to the latest version.
`None`
`None`

chore: update csi-snapshotter to v8.2.0

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml

Issue longhorn/longhorn#9898
Update external components.
`None`
`None`

chore(cve): update external components

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#9895
Resolve CVE issues for v1.8.0-rc1 release.
- Backport to v1.8.x.
`None`

chore(cve): update image versions

---

.github/ISSUE_TEMPLATE/release.md

chore: update Release Task template

---

enhancements/20241203-v2-backing-image-support.md

ref: https://github.com/longhorn/longhorn/issues/6341
LEP for v2 backing image

docs: add lep for v2 backing image support

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.4-rc1

---

chart/README.md
chart/templates/deployment-driver.yaml
chart/values.yaml

Which issue(s) this PR fixes:
Issue https://github.com/longhorn/longhorn/issues/10064
What this PR does / why we need it:
Added support for JSON log format configuration in Longhorn-driver
Special notes for your reviewer:
Additional documentation or context

feat(chart): added-choice-of-log-format-json-for-deployment-driver

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.4-rc2

---

.github/workflows/backport-pr.yml

ref: https://github.com/longhorn/longhorn/issues/9764#issuecomment-2567254532

fix(gh-action): reference PR to right backport issues

---

chart/README.md

docs: update versions in chart/README.md

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.6.4

---

CHANGELOG/CHANGELOG-1.6.4.md

docs: add v1.6.4 release note

---

README.md

docs: add v1.6.4 in README.md

---

.github/workflows/update-branch-image-tags.yaml

chore(workflow): update Longhorn repository branch image tags

---

.github/workflows/update-branch-image-tags.yaml

chore(workflow): add sign-off for Longhorn repository branch image tags

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

chore: update crds.yaml and manifests

---

deploy/upgrade_responder_server/chart-values.yaml

chore: release longhorn v1.6.4 into upgrade responder server

---

chart/README.md
chart/questions.yaml
chart/values.yaml

Issue # longhorn/longhorn#5411, longhorn/longhorn#10089
And update the chart README.md

chore: update questions.yaml according to values.yaml

---

.github/workflows/validate-yamls.yaml
chart/questions.yaml

chore(workflow): validate questions.yaml

---

chart/README.md

chore(chart): update chart/README.md

---

.github/workflows/update-branch-image-tags.yaml

fix(workflow): fix the format of committer

---

chart/Chart.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

chore(chart): bump to v1.9.0-dev

---

README.md

docs(v1.8.0): update README.md

---

chart/README.md
chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3516.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3516)

---

.github/ISSUE_TEMPLATE/fix-cve-issues-for-release.md
.github/ISSUE_TEMPLATE/regular-tasks-for-feature-release.md
.github/ISSUE_TEMPLATE/release.md
.github/workflows/create-release-task-issues.yml

Issue #
- add create-release-task-issues.yml
- update templates for release tasks

chore: update templates for release tasks and add a workflow

---

chart/templates/default-setting.yaml

Issue https://github.com/longhorn/longhorn/issues/10323
Make name in default settings configmap match name in settings.

fix: correct name in default settings configmap

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
enhancements/20240423-longhorn-commandline-interface.md

Issue longhorn/longhorn#9897
`None`
`None`

chore(cve): update images

---

CHANGELOG/CHANGELOG-1.8.0.md

chore: add PSA to v1.8.0

---

.github/ISSUE_TEMPLATE/release.md

Issue Longhorn/longhorn#10314
Added "Update Longhorn Repository Branch Image Tags" action item. The item should be executed after a release.

chore: update release.md template

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3532.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3532)

---

.github/workflows/scorecards.yml

fix(workflow): fix "Scorecard supply-chain security"

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#9897
`None`
`None`

chore(cve): update support-bundle-kit to v0.0.51

---

chart/README.md

docs(1.7.3): update chart/README.md

---

README.md

docs(1.7.3): update README.md

---

CHANGELOG/CHANGELOG-1.7.3.md

docs(1.7.3): add CHANGELOG

---

chart/questions.yaml

docs: update description for upgradeResponderURL

---

deploy/upgrade_responder_server/chart-values.yaml

chore: release longhorn v1.7.3 into upgrade responder server

---

chart/README.md

chore(v1.8.1): update chart/README.md

---

CHANGELOG/CHANGELOG-1.8.1.md

docs(1.8.1): add CHANGELOG

---

README.md

chore(1.8.1): update Releases in README.md

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Issue longhorn/longhorn#7047
Add hostArch and longhornVolumeEncrypted*Count to requestSchema.
`None`
Dependent on https://github.com/longhorn/longhorn-manager/pull/3617.

feat(upgrade_responder): add hostArch and longhornVolumeEncrypted*Count

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#6754
Update support-bundle-kit to collect /proc/mounts and multipath.conf.
`None`
`None`

chore: update support-bundle-kit to v0.0.53

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Issue longhorn/longhorn#7599
Add request schemas:
- longhornVolumeNumberOfReplicas
- longhornVolumeNumberOfSnapshots
- longhornBackingImageCount
- longhornOrphanCount
Dependent on https://github.com/longhorn/longhorn-manager/pull/3618.
`None`

feat(upgrade_responder): add request schemas

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3616.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3616)

---

chart/questions.yaml
chart/templates/storageclass.yaml
chart/values.yaml

fix(chart): allow for setting volumeBindingMode from helm values

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3505.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3505)

---

chart/questions.yaml

feat(setting): remove ValueIntRangeMaximum of v2-data-engine-guaranteed-instance-manager-cpu

---

deploy/upgrade_responder_server/chart-values.yaml

chore: release Longhorn v1.8.1 to the upgrade responder

---

chart/templates/clusterrole.yaml
chart/templates/clusterrolebinding.yaml
chart/templates/deployment-ui.yaml

Issue #10681
Fixes some non fatal syntax errors
These are non fatal syntax errors but they should be addressed
N/A

fix: minor issues found with `yamllint`

---

scripts/update-uninstall-manifest.py
uninstall/uninstall.yaml

Issue Longhorn/longhorn#5137
To prevent the update of CRDs, uninstall.yaml will be regenerated from deploy/longhorn.yaml.
The python file will be executed by the workflow in https://github.com/longhorn/longhorn-manager/pull/3486.

chore(script): regenerate uninstall.yaml from deploy/longhorn.yaml

---

deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3669.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3669)

---

chart/README.md
chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3631.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3631)

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3650.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3650)

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#23.

chore(chart): update dependency versions (PR longhorn/dep-versions#23)

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3648.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3648)

---

deploy/longhorn-images.txt

Issue longhorn/longhorn#10774
Fix typo.
`None`
`None`

fix(deploy): typo

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3715.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3715)

---

.github/ISSUE_TEMPLATE/release.md

chore(templete): update release.md

---

.github/workflows/update-community-review-sprint-issue-status.yaml

chore(workflow): fix update-community-review-sprint-issue-status.yaml

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.9.0-rc1

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3737.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3737)

---

chart/templates/extra-objects.yaml
chart/values.yaml

Issue https://github.com/longhorn/longhorn/issues/10835
sometime we want to include some other CR during helm install
avoid create a Kustomize for that 
is quite classic this behaviour on others charts

feat(charts): add extraObjects values

---

chart/values.yaml

It was triggered by longhorn/dep-versions#30.

chore(chart): update dependency versions (PR longhorn/dep-versions#30)

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.9.0-rc2

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Issue Longhorn/longhorn#10875
Replace longhornSettingOrphanAutoDeletion with longhornSettingOrphanResourceAutoDeletion.

chore: update install.sh in upgrade-responder

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3768.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3768)

---

deploy/backupstores/nfs-backupstore.yaml

Issue longhorn/longhorn#10878
https://github.com/longhorn/nfs-backupstore/pull/2#issuecomment-2878287718
`None`
`None`

fix(backupstore/nfs): ganesha recovery state error

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#10913
`None`
`None`

chore(cve): update support-bundle-kit to v0.0.54

---

chart/questions.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

feat(setting): add orphan-resource-auto-deletion-grace-period setting

---

examples/snapshot/existing_backup.yaml

fix: update existing_backup.yaml

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.9.0-rc3

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#40.

chore(chart): update dependency versions (PR longhorn/dep-versions#40)

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3794.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3794)

---

chart/templates/storageclass.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue # longhorn/longhorn#10961

fix(backup): add 'backupTargetName' in chart/templates/storageclass.yaml

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.9.0-rc4

---

chart/README.md

It was triggered by longhorn/dep-versions#52.

chore(chart): update dependency versions (PR longhorn/dep-versions#52)

---

.github/ISSUE_TEMPLATE/hotfix.md
.github/ISSUE_TEMPLATE/release.md

chore(template): add HOTFIX template

---

CHANGELOG/CHANGELOG-1.9.0.md
README.md

docs(v1.9.0): add CHANGELOG

---

CHANGELOG/CHANGELOG-1.8.2.md

docs(1.8.2): add release note

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3779.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3779)

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3828.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3828)

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

Issue longhorn/longhorn#10913
Update dependent component versions.
`None`
`None`

chore: update dependent component image versions

---

chart/templates/crds.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3804.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3804)

---

chart/templates/daemonset-sa.yaml
chart/templates/network-policies/webhook-network-policy.yaml
chart/templates/services.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
examples/network-policy/webhook-network-policy.yaml

feat(crd): remove v1beta1 api

---

CHANGELOG/CHANGELOG-1.8.2.md

docs(1.8.2): update release note

---

chart/README.md

It was triggered by longhorn/longhorn-manager#3840.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3840)

---

chart/questions.yaml

It was triggered by longhorn/dep-versions#55.

chore(chart): update dependency versions (PR longhorn/dep-versions#55)

---

chart/README.md

docs(1.8.2): update chart/README.md

---

README.md

docs(1.8.2): update README.md

---

.github/workflows/pr-review-reminder.py

fix(workflow): fix links of pull requests

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#68.

chore(chart): update dependency versions (PR longhorn/dep-versions#68)

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#69.

chore(chart): update dependency versions (PR longhorn/dep-versions#69)

---

chart/README.md
chart/questions.yaml
chart/templates/crds.yaml
chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/longhorn-manager#3736.

chore(crd): update crds.yaml and manifests (PR longhorn/longhorn-manager#3736)

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#72.

chore(chart): update dependency versions (PR longhorn/dep-versions#72)

---

chart/README.md
chart/questions.yaml
chart/values.yaml

fix(doc): clarify privateRegistry.createSecret and registrySecret usage in chart description

---

.github/workflows/update-community-issue.yml

chore(workflow): use LONGHORN_GITHUB_BOT_TOKEN for update-community-issue.yml

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#74.

chore(chart): update dependency versions (PR longhorn/dep-versions#74)

---

.github/workflows/update-community-issue.yml
.github/workflows/update-longhorn-issue.yml

chore(workflow): add "permission-members: read"

---

.github/workflows/add-issue-to-projects.yml
.github/workflows/backport-pr.yml
.github/workflows/conventional-commits.yml
.github/workflows/create-issue.yml
.github/workflows/create-release-task-issues.yml
.github/workflows/periodic-issue-sprint-update.yml
.github/workflows/pr-review-reminder.yml
.github/workflows/scan-and-notify-testing-items.yml
.github/workflows/update-branch-image-tags.yaml

chore(workflow): replace PAT with longhorn-github-bot APP Token

---

.github/workflows/backport-pr.yml
.github/workflows/periodic-issue-sprint-update.yml
.github/workflows/pr-review-reminder.yml
.github/workflows/update-community-issue.yml
.github/workflows/update-longhorn-issue.yml

chore(workflow): add permission-organization-projects to workflows

---

.github/workflows/add-issue-to-projects.yml
.github/workflows/pr-review-reminder.yml

chore(workflow): fix permission errors

---

.github/workflows/update-longhorn-issue.yml

chore(workflow): github-actions[bot] should be longhorn memeber

---

.github/workflows/backport-pr.yml

fix: improve workflow

---

chart/questions.yaml

It was triggered by longhorn/dep-versions#81.

chore(chart): update dependency versions (PR longhorn/dep-versions#81)

---

.github/workflows/create-issue.yml

fix(workflow): add backport ticket to Longhorn Sprint

---

.github/workflows/add-issue-to-projects.yml

fix(workflow): fix add-issue-to-projects.yml

---

enhancements/20250721-v2-engine-interrupt-mode.md

Issue longhorn/longhorn#9834
Propose supporting interrupt mode for Longhorn V2 engine to reduce CPU consumption.
`None`
`None`

feat(lep): v2 engine - interrupt mode

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Issue Longhorn/longhorn#11792
Collect Longhorn image registry to understand the installation variants.

feat: collect Longhorn image registry

---

deploy/upgrade_responder_server/chart-values.yaml
dev/upgrade-responder/install.sh

Issue `None`
https://github.com/longhorn/longhorn/pull/11513/files

fix(upgrade-responder): invalid char

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.10.0-rc3

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.9.2-rc2

---

chart/templates/default-setting.yaml
chart/values.yaml
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
enhancements/20250508-v2-volume-cloning.md

fix(settings): quote values of settings

---

chart/README.md
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml

It was triggered by longhorn/dep-versions#114.

chore(chart): update dependency versions (PR longhorn/dep-versions#114)

---

chart/README.md

chore(1.9.2): update chart/README.md

---

CHANGELOG/CHANGELOG-1.9.2.md
README.md

chore(1.9.2): update README.md and add CHANGELOG-1.9.2.md

---

chart/templates/default-setting.yaml

fix(setting): no need to check boolean settings

---

chart/Chart.yaml
chart/questions.yaml
chart/values.yaml
deploy/longhorn-images.txt
deploy/longhorn-okd.yaml
deploy/longhorn.yaml
uninstall/uninstall.yaml

release: v1.10.0

---

CHANGELOG/CHANGELOG-1.10.0.md
README.md

chore(1.10.0): update README and add CHANGELOG

---

deploy/upgrade_responder_server/chart-values.yaml
deploy/upgrade_responder_server/chart.yaml

longhorn/longhorn#11547
longhorn/longhorn#11699

chore: release v1.10.0 and v1.9.2 to upgrade responder
